package:
  name: covjsonkit
  version: 0.1.4
  top-level:
    - covjsonkit
source:
  url: https://files.pythonhosted.org/packages/d0/1b/a83e9f40f65b6159542c3edf6bb9fe35ea7bcc8e739a7cbc36ff20947ca0/covjsonkit-0.1.4.tar.gz
  sha256: 67ff8c8e2153c121875d524b1cc4c95c914dae2c87b1e648aeeea134841cd241
requirements:
  run:
    - pandas
    - orjson
    - xarray
    - pandas
    - covjson-pydantic
    - conflator
about:
  home: https://github.com/ecmwf/covjsonkit
  PyPI: https://pypi.org/project/covjsonkit
  summary:
    ECMWF library for encoding and decoding coerageJSON files/objects of meteorlogical
    features such as vertical profiles and time series.
  license: Apache License Version 2.0
