package:
  name: libudunits2
  version: 2.2.28

source:
  url: https://downloads.unidata.ucar.edu/udunits/2.2.28/udunits-2.2.28.tar.gz
  sha256: 590baec83161a3fd62c00efa66f6113cec8a7c461e3f61a5182167e0cc5d579e
  patches:
    - patches/0001-expat-xml-stopparser.patch
    - patches/0002-udunits2-xml-path.patch

requirements:
  host:
    - libexpat

build:
  type: static_library
  script: |
    mkdir -p build;

    emconfigure ./configure --prefix=${WASM_LIBRARY_DIR};

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=off;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libudunits2.a ${DISTDIR}
