package:
  name: lz4
  version: 4.4.4
  top-level:
    - lz4
source:
  url: https://files.pythonhosted.org/packages/cc/bc/b2e79af05be82841706ddd7d78059e5f78e6ca5828f92034394b54e303b7/lz4-4.4.4.tar.gz
  sha256: 070fd0627ec4393011251a094e08ed9fdcc78cb4e7ab28f507638eee4e39abda
about:
  home: https://github.com/python-lz4/python-lz4
  PyPI: https://pypi.org/project/lz4
  summary: LZ4 Bindings for Python
  license: BSD 3-Clause License
