package:
  name: intake-xarray
  version: 2.0.0
  top-level:
    - intake_xarray
source:
  url: https://files.pythonhosted.org/packages/9d/d9/a33d0c2ad75bd0f67929411883fb251f9c72f12880744a4ee5b8331cb35b/intake_xarray-2.0.0-py3-none-any.whl
  sha256: 9693cf8524a7cd63bb7c734e65aafd97e0f1abbbaf4f9bf9a57e86d8882ea339
requirements:
  run:
    - dask
    - fsspec
    - intake
    - msgpack
    - netCDF4
    - requests
    - xarray
    - zarr
about:
  home: https://github.com/intake/intake-xarray
  PyPI: https://pypi.org/project/intake-xarray
  summary: xarray plugins for Intake
  license: BSD
