package:
  name: hda
  version: "2.22"
  top-level:
    - hda
source:
  url: https://files.pythonhosted.org/packages/source/h/hda/hda-2.22.tar.gz
  sha256: b20b87347117e653ef6892e3ae6a5600a1a1da1e9b453bd2f002a87c906b9598
about:
  home: https://github.com/ecmwf/hda
  PyPI: https://pypi.org/project/hda
  summary: API to harmonised data access for DIAS/WEkEO
  license: Apache 2.0
