package:
  name: pyodc
  version: 1.5.0
  top-level:
    # - codc
    - pyodc
source:
  url: https://files.pythonhosted.org/packages/source/p/pyodc/pyodc-1.5.0.tar.gz
  sha256: 78dce79ef8eb0b75dc7bf5988dcd88f77d1c8319d969bbef21dbfe268e0b5b12
  patches:
    - patches/0001-only-pyodc.patch
requirements:
  run:
    # - cffi  # only for codc
    - pandas
about:
  home: https://github.com/ecmwf/pyodc
  PyPI: https://pypi.org/project/pyodc
  summary: A Python interface to odc for encoding/decoding ODB-2 files.
  license: Apache License Version 2.0
