package:
  name: pyodc
  version: 1.6.0
  top-level:
    # - codc
    - pyodc
source:
  url: https://files.pythonhosted.org/packages/source/p/pyodc/pyodc-1.6.0.tar.gz
  sha256: 702ce63f91e5a0ac75812c1b7a298c7bc95e7287531155f8a6e10ca31cd345aa
  patches:
    - patches/0001-only-pyodc.patch
requirements:
  run:
    # - cffi  # only for codc
    # - findlibs  # only for codc
    - pandas
about:
  home: https://github.com/ecmwf/pyodc
  PyPI: https://pypi.org/project/pyodc
  summary: A Python interface to odc for encoding/decoding ODB-2 files.
  license: Apache License Version 2.0
