package:
  name: regex
  version: 2024.11.6
  tag:
    - core
    - min-scipy-stack
  top-level:
    - regex
source:
  sha256: 7ab159b063c52a0333c884e4679f8d7a85112ee3078fe3d9004b2dd875585519
  url: https://files.pythonhosted.org/packages/source/r/regex/regex-2024.11.6.tar.gz
about:
  home: https://github.com/mrabarnett/mrab-regex
  PyPI: https://pypi.org/project/regex
  summary: Alternative regular expression module, to replace re.
  license: Apache-2.0
