package:
  name: sharedlib-test-py
  version: "1.0"
  tag:
    - core
    - pyodide.test
  top-level:
    - sharedlib_test
requirements:
  host:
    - sharedlib-test
source:
  path: src
build:
  vendor-sharedlib: true
  cross-script: |
    pwd
    echo PYTHONPATH: $PYTHONPATH
    echo _PYTHON_HOST_PLATFORM: $_PYTHON_HOST_PLATFORM
  cflags: |
    -I$(PKGDIR)/../sharedlib-test/src/include
  ldflags: |
    $(PKGDIR)/../sharedlib-test/build/sharedlib-test-1.0/dist/sharedlib-test.so
about:
  license: MPL-2.0
