package:
  name: pyproj
  version: 3.7.0
  top-level:
    - pyproj
source:
  url: https://files.pythonhosted.org/packages/47/c2/0572c8e31aebf0270f15f3368adebd10fc473de9f09567a0743a3bc41c8d/pyproj-3.7.0.tar.gz
  sha256: bf658f4aaf815d9d03c8121650b6f0b8067265c36e31bc6660b98ef144d81813

requirements:
  host:
    - libproj
  run:
    - certifi
    - sqlite3

build:
  script: |
    embuilder build sqlite3 --pic

    export PROJ_VERSION=9.3.1
    export PROJ_DIR=${WASM_LIBRARY_DIR}
    export PROJ_INCDIR=${WASM_LIBRARY_DIR}/include
    export PROJ_LIBDIR=${WASM_LIBRARY_DIR}/lib
    export PROJ_WHEEL=1
    mkdir -p pyproj/proj_dir/share
    cp -r ${WASM_LIBRARY_DIR}/share/proj pyproj/proj_dir/share
  cflags: |
    -sUSE_SQLITE3
  ldflags: |
    -sUSE_SQLITE3
    -lsqlite3
test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  PyPI: https://pypi.org/project/pyproj/
  summary:
    Python interface to PROJ (cartographic projections and coordinate transformations
    library)
  license: MIT
