package:
  name: pydantic
  version: 2.10.5
  top-level:
    - pydantic
source:
  sha256: 4dd4e322dbe55472cb7ca7e73f4b63574eecccf2835ffa2af9021ce113c83c53
  url: https://files.pythonhosted.org/packages/58/26/82663c79010b28eddf29dcdd0ea723439535fa917fce5905885c0e9ba562/pydantic-2.10.5-py3-none-any.whl
requirements:
  run:
    - typing_extensions
    - pydantic_core
    - annotated-types
about:
  home: https://github.com/samuelcolvin/pydantic
  PyPI: https://pypi.org/project/pydantic
  summary: Data validation and settings management using python type hints
  license: MIT
