package:
  name: h5netcdf
  version: 1.4.1
  top-level:
    - h5netcdf
requirements:
  run:
    - h5py
    - packaging
source:
  url: https://files.pythonhosted.org/packages/2a/bd/7f13482400f0cab61f8daff9048b040899010002ae705532cce8fc8c948d/h5netcdf-1.4.1-py3-none-any.whl
  sha256: dd86c78ae69b92b16aa8a3c1ff3a14e7622571b5788dcf6d8b68569035bf71ce
about:
  home: https://github.com/h5netcdf/h5netcdf
  PyPI: https://pypi.org/project/h5netcdf
  summary: netCDF4 via h5py
  license: BSD-3-Clause
