package:
  name: h5netcdf
  version: 1.4.0
  top-level:
    - h5netcdf
requirements:
  run:
    - h5py
    - packaging
source:
  url: https://files.pythonhosted.org/packages/73/05/0ad1bb1305de0278457e28069a91c5d03f9e2d014e54ac505abfa56ba3e7/h5netcdf-1.4.0-py3-none-any.whl
  sha256: d1bb96fce5dcf42908903c9798beeef70ac84e97159eb381f1b151459313f228
about:
  home: https://github.com/h5netcdf/h5netcdf
  PyPI: https://pypi.org/project/h5netcdf
  summary: netCDF4 via h5py
  license: BSD-3-Clause
