package:
  name: pytest-benchmark
  version: 5.1.0
  top-level:
    - pytest_benchmark
source:
  url: https://files.pythonhosted.org/packages/39/d0/a8bd08d641b393db3be3819b03e2d9bb8760ca8479080a26a5f6e540e99c/pytest-benchmark-5.1.0.tar.gz
  sha256: 9ea661cdc292e8231f7cd4c10b0319e56a2118e2c09d9f50e1b3d150d2aca105
  patches:
    - patches/0001-Remove-cpuinfo.patch
requirements:
  run:
    - pytest
about:
  home: https://github.com/ionelmc/pytest-benchmark
  PyPI: https://pypi.org/project/pytest-benchmark
  summary:
    A ``pytest`` fixture for benchmarking code. It will group the tests into
    rounds that are calibrated to the chosen timer.
  license: BSD-2-Clause
