package:
  name: pydantic_core
  version: 2.33.0
  tag:
    - rust
  # Warning: pydantic has a pin on pydantic_core, they need to be updated
  # together
  top-level:
    - pydantic_core
source:
  url: https://files.pythonhosted.org/packages/source/p/pydantic_core/pydantic_core-2.33.0.tar.gz
  sha256: 40eb8af662ba409c3cbf4a8150ad32ae73514cd7cb1f1a2113af39763dd616b3
requirements:
  executable:
    - rustup
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
