package:
  name: pydantic_core
  version: 2.27.2
  top-level:
    - pydantic_core
source:
  url: https://github.com/pydantic/pydantic-core/releases/download/v2.27.2/pydantic_core-2.27.2-cp312-cp312-emscripten_3_1_58_wasm32.whl
  sha256: cf0a64dd4f748d6bf12b71f8c3502242191c414d9519ed59b33feff8b1e18b9c
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
