package:
  name: Webob
  version: 1.8.9
  top-level:
    - webob
source:
  url: https://files.pythonhosted.org/packages/50/bd/c336448be43d40be28e71f2e0f3caf7ccb28e2755c58f4c02c065bfe3e8e/WebOb-1.8.9-py2.py3-none-any.whl
  sha256: 45e34c58ed0c7e2ecd238ffd34432487ff13d9ad459ddfd77895e67abba7c1f9
about:
  home: http://webob.org/
  PyPI: https://pypi.org/project/Webob
  summary: WSGI request and response object
  license: MIT
