package:
  name: propcache
  version: 0.2.1
  top-level:
    - propcache
source:
  url: https://files.pythonhosted.org/packages/41/b6/c5319caea262f4821995dca2107483b94a3345d4607ad797c76cb9c36bcc/propcache-0.2.1-py3-none-any.whl
  sha256: 52277518d6aae65536e9cea52d4e7fd2f7a66f4aa2d30ed3f2fcea620ace3c54
about:
  home: https://github.com/aio-libs/propcache
  PyPI: https://pypi.org/project/propcache
  summary: Accelerated property cache
  license: Apache-2.0
