package:
  name: conflator
  version: 0.1.5
  top-level:
    - conflator
source:
  url: https://files.pythonhosted.org/packages/10/30/1713cf59cd9293af0eec7a8af7b2765fe7795b438a5af0f26aab76eb94e5/conflator-0.1.5-py3-none-any.whl
  sha256: cae382e17e3a6362d7b8597040e28ea479e5a7ac89cebeeaa52f745c621487c9
requirements:
  run:
    - pydantic
    - rich
    - rich-argparse
    - pyyaml
about:
  home: https://github.com/ecmwf/conflator/
  PyPI: https://pypi.org/project/conflator
  summary:
    Load small app configurations from environment variables, command line
    arguments and config files, according to a pydantic model.
  license: Apache-2.0
