package:
  name: earthkit
  version: 0.6.2
  top-level:
    - earthkit
source:
  url: https://files.pythonhosted.org/packages/5d/0c/757c585b05a441e161c6e0bc6b5fb794b331197c77980e4b4322e08424fa/earthkit-0.6.2-py3-none-any.whl
  sha256: ba2b524acd3043d4abc0f5759c410251b2d61cefe9941a261ef33ee000862716
requirements:
  run:
    - numpy
    - earthkit-data
    - earthkit-geo
    - earthkit-maps
    - earthkit-meteo
    - earthkit-plots
    - earthkit-regrid
    - earthkit-transforms
about:
  home: https://github.com/ecmwf/earthkit
  PyPI: https://pypi.org/project/earthkit
  license: Apache License 2.0
