package:
  name: earthkit
  version: 0.8.0
  top-level:
    - earthkit
source:
  url: https://files.pythonhosted.org/packages/81/a8/cc01d4712243180247788746cbe4890e824c492bf063d5dfbb929f506613/earthkit-0.8.0-py3-none-any.whl
  sha256: 2b16fdd2bb6ed1473b728cde6d6f845e5afc50ea20c9346b83a4a9d5d5df4226
requirements:
  run:
    - earthkit-data
    - earthkit-geo
    - earthkit-meteo
    - earthkit-plots
    - earthkit-regrid
    - earthkit-transforms
about:
  home: https://github.com/ecmwf/earthkit
  PyPI: https://pypi.org/project/earthkit
  license: Apache License 2.0
