package:
  name: earthkit
  version: 0.9.1
  top-level:
    - earthkit
source:
  url: https://files.pythonhosted.org/packages/6c/c3/19abe0c506dfc962404770bf295bbe427f912044e012acbc2ab91b96db1f/earthkit-0.9.1-py3-none-any.whl
  sha256: 6901bafc182fb1ee8b6d2c28ab69e1158510cf6dcbbc78bf24b7f5fd3c81d6fc
requirements:
  run:
    - earthkit-data
    - earthkit-geo
    - earthkit-meteo
    - earthkit-plots
    - earthkit-regrid
    - earthkit-transforms
about:
  home: https://github.com/ecmwf/earthkit
  PyPI: https://pypi.org/project/earthkit
  license: Apache License 2.0
