package:
  name: tzdata
  version: 2024.2
  top-level:
    - tzdata
source:
  url: https://files.pythonhosted.org/packages/a6/ab/7e5f53c3b9d14972843a647d8d7a853969a58aecc7559cb3267302c94774/tzdata-2024.2-py2.py3-none-any.whl
  sha256: a48093786cdcde33cad18c2555e8532f34422074448fbc874186f0abd79565cd
about:
  home: https://github.com/python/tzdata
  PyPI: https://pypi.org/project/tzdata
  summary: Provider of IANA time zone data
  license: Apache-2.0
