package:
  name: earthkit-data
  version: 0.13.7
  top-level:
    - earthkit.data
source:
  url: https://files.pythonhosted.org/packages/source/e/earthkit_data/earthkit_data-0.13.7.tar.gz
  sha256: 2046973c6ddff6f8bd5066a439e326697dcf70ab3de4dad6075896137578580e
  patches:
    - patches/0001-no-pyfdb.patch
requirements:
  run:
    - Cartopy           # optional
    - eccodes           # required, not loaded immediately
    - hda               # optional
    - lru-dict          # required, not loaded immediately
    - netCDF4           # required, not loaded immediately
    - pandas            # required, not loaded immediately
    # - pyfdb  # TODO   # optional
    - pyodc             # optional
    - PyYAML            # required
about:
  home: https://github.com/ecmwf/earthkit-data
  PyPI: https://pypi.org/project/earthkit-data
  summary: A format-agnostic Python interface for geospatial data
  license: Apache License 2.0
