package:
  name: earthkit-data
  version: 0.11.4
  top-level:
    - earthkit.data
source:
  url: https://files.pythonhosted.org/packages/4a/56/ed72b8d129185c2cd06d834806afe9d49800d004a10f249a453e36fa0777/earthkit_data-0.11.4.tar.gz
  sha256: 14abb50a647fccfbd2e14b5d5d9444ab51fced8d1a3afb011664fbfc62b50e9a
  patches:
    - patches/0001-no-pyfdb.patch
requirements:
  run:
    - array-api-compat  # required, not loaded immediately
    - Cartopy           # optional
    - cdsapi            # optional
    - cfgrib            # required, not loaded immediately
    - covjsonkit        # optional
    - dask              # required, not loaded immediately
    - earthkit-geo      # required, not loaded immediately
    - earthkit-meteo    # required, not loaded immediately
    - eccodes           # required, not loaded immediately
    - ecmwf-api-client  # optional
    - ecmwf-opendata    # optional
    - entrypoints       # required
    - filelock          # required, not loaded immediately
    - geopandas         # optional
    - hda               # optional
    - Jinja2            # required, not loaded immediately
    - jsonschema        # required, not loaded immediately
    - lru-dict          # required, not loaded immediately
    - markdown          # required, not loaded immediately
    - multiurl          # required, not loaded immediately
    - netcdf4           # required, not loaded immediately
    - pandas            # required, not loaded immediately
    - pdbufr            # optional
    - polytope-client   # optional
    # - pyfdb  # TODO   # optional
    - pyodc             # optional
    - pyyaml            # required
    - tqdm              # required, not loaded immediately
    - xarray            # required, not loaded immediately
about:
  home: https://github.com/ecmwf/earthkit-data
  PyPI: https://pypi.org/project/earthkit-data
  summary: A format-agnostic Python interface for geospatial data
  license: Apache License 2.0
