package:
  name: earthkit-data
  version: 0.11.4
  top-level:
    - earthkit.data
source:
  url: https://files.pythonhosted.org/packages/5d/f0/b6634b47b2d4cf3a9aa21ef5b4db6d96cc8a912391fdb3f3ed1b9618267c/earthkit_data-0.11.4-py3-none-any.whl
  sha256: 490ca5a843e840753bfc2dc9b8b4e7366f4d9342f71995c866c7aea5c015fc27
requirements:
  run:
    - array-api-compat  # required, not loaded immediately
    - Cartopy           # optional
    - cdsapi            # optional
    - cfgrib            # required, not loaded immediately
    - covjsonkit        # optional
    - dask              # required, not loaded immediately
    - earthkit-geo      # required, not loaded immediately
    - earthkit-meteo    # required, not loaded immediately
    - eccodes           # required, not loaded immediately
    - ecmwf-api-client  # optional
    - ecmwf-opendata    # optional
    - entrypoints       # required
    - filelock          # required, not loaded immediately
    - geopandas         # optional
    - hda               # optional
    - Jinja2            # required, not loaded immediately
    - jsonschema        # required, not loaded immediately
    - lru-dict          # required, not loaded immediately
    - markdown          # required, not loaded immediately
    - multiurl          # required, not loaded immediately
    - netcdf4           # required, not loaded immediately
    - pandas            # required, not loaded immediately
    - pdbufr            # optional
    - polytope-client   # optional
    # - pyfdb  # TODO   # optional
    - pyodc             # optional
    - pyyaml            # required
    - tqdm              # required, not loaded immediately
    - xarray            # required, not loaded immediately
about:
  home: https://github.com/ecmwf/earthkit-data
  PyPI: https://pypi.org/project/earthkit-data
  summary: A format-agnostic Python interface for geospatial data
  license: Apache License 2.0
