package:
  name: earthkit-data
  version: 0.10.8
  top-level:
    - earthkit.data
source:
  url: https://files.pythonhosted.org/packages/7a/ee/e67fdcf0c41fd3c4ab23ffceefdf4fcbadb375d9f7622db764ec51357f95/earthkit_data-0.10.8-py3-none-any.whl
  sha256: 0f550f12f2855aa8cf58a0a91bdec47163cb73eeaf79247522756e4e4e657c27
requirements:
  run:
    - Cartopy
    - cdsapi
    - cfgrib
    - dask
    - earthkit-geo
    - earthkit-meteo
    - eccodes
    - ecmwf-api-client
    - ecmwf-opendata
    - entrypoints
    - filelock
    - geopandas
    - Jinja2
    - jsonschema
    - lru-dict
    - markdown
    - multiurl
    - netcdf4
    - pandas
    - pdbufr
    - pyyaml
    - tqdm
    - xarray
about:
  home: https://github.com/ecmwf/earthkit-data
  PyPI: https://pypi.org/project/earthkit-data
  summary: A format-agnostic Python interface for geospatial data
  license: Apache License 2.0
