package:
  name: earthkit-data
  version: 0.11.4
  top-level:
    - earthkit.data
source:
  url: https://files.pythonhosted.org/packages/5d/f0/b6634b47b2d4cf3a9aa21ef5b4db6d96cc8a912391fdb3f3ed1b9618267c/earthkit_data-0.11.4-py3-none-any.whl
  sha256: 490ca5a843e840753bfc2dc9b8b4e7366f4d9342f71995c866c7aea5c015fc27
requirements:
  run:
    - array-api-compat
    - Cartopy
    - cdsapi
    - cfgrib
    - dask
    - earthkit-geo
    - earthkit-meteo
    - eccodes
    - ecmwf-api-client
    - ecmwf-opendata
    - entrypoints
    - filelock
    - geopandas
    - hda
    - Jinja2
    - jsonschema
    - lru-dict
    - markdown
    - multiurl
    - netcdf4
    - pandas
    - pdbufr
    - pyyaml
    - tqdm
    - xarray
about:
  home: https://github.com/ecmwf/earthkit-data
  PyPI: https://pypi.org/project/earthkit-data
  summary: A format-agnostic Python interface for geospatial data
  license: Apache License 2.0
