package:
  name: earthkit-meteo
  version: 0.3.0
  top-level:
    - earthkit.meteo
source:
  url: https://files.pythonhosted.org/packages/72/6c/b809322ae3405803e5957fa4ea495955689a300a107f0727c70f91f29865/earthkit_meteo-0.3.0-py3-none-any.whl
  sha256: 2aec3ff6a505dcb129fbbafc7b20d7868420c82eb7e7229c7d7679a87b2efcd4
requirements:
  run:
    - numpy
about:
  home: https://github.com/ecmwf/earthkit-meteo
  PyPI: https://pypi.org/project/earthkit-meteo
  summary: Meteorological computations
  license: Apache License 2.0
