package:
  name: partd
  version: 1.4.2
  top-level:
    - partd
source:
  url: https://files.pythonhosted.org/packages/71/e7/40fb618334dcdf7c5a316c0e7343c5cd82d3d866edc100d98e29bc945ecd/partd-1.4.2-py3-none-any.whl
  sha256: 978e4ac767ec4ba5b86c6eaa52e5a2a3bc748a2ca839e8cc798f1cc6ce6efb0f
requirements:
  run:
    - locket
    - toolz
about:
  home: http://github.com/dask/partd/
  PyPI: https://pypi.org/project/partd
  summary: Appendable key-value storage
  license: BSD
