package:
  name: intake-esm
  version: 2025.2.3
  top-level:
    - intake_esm
source:
  url: https://files.pythonhosted.org/packages/da/58/7727592d0c72bfd3ad83144e53d3c2ff5f1c7fa2f0f42b183405574e32ff/intake_esm-2025.2.3-py3-none-any.whl
  sha256: c836df7be119806894f98fb86f36697cfd05e49c68c5b2418cb89ed696ac478c
requirements:
  run:
    - dask
    - fastprogress
    - fsspec
    - intake
    - netCDF4
    - pandas
    - pydantic
    - requests
    - xarray
    - zarr
about:
  home: https://github.com/intake/intake-esm
  PyPI: https://pypi.org/project/intake-esm
  summary:
    An intake plugin for parsing an Earth System Model (ESM) catalog and loading
    netCDF files and/or Zarr stores into Xarray datasets.
  license: Apache 2.0
