package:
  name: kerchunk
  version: 0.2.6
  top-level:
    - kerchunk
source:
  url: https://files.pythonhosted.org/packages/82/8c/117feba86c75d42b8434f8e65085165df4cd415c754bcde3df007f036293/kerchunk-0.2.6-py3-none-any.whl
  sha256: dc55fcea6560688ffc2390ff5882847fdf736982c1817553632a2bd7eb59de73
requirements:
  run:
    - fsspec
    - numcodecs
    - numpy
    - ujson
    - zarr
    - cftime
    - xarray
    - h5py
    - cfgrib
    - scipy
about:
  home: https://github.com/fsspec/kerchunk
  PyPI: https://pypi.org/project/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
