package:
  name: kerchunk
  version: 0.2.7
  top-level:
    - kerchunk
source:
  url: https://files.pythonhosted.org/packages/e1/c9/1280fa083aee51224327a44ffcd6037b1c6ed914159e46757be631b3f776/kerchunk-0.2.7-py3-none-any.whl
  sha256: 9c0b4f721d0d6fef93fb5ffd3e0906d7a776bb19fb8347c02449899972c9b48c
requirements:
  run:
    - fsspec
    - numcodecs
    - numpy
    - ujson
    - zarr
    - cftime
    - xarray
    - h5py
    - cfgrib
    - scipy
about:
  home: https://github.com/fsspec/kerchunk
  PyPI: https://pypi.org/project/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
