package:
  name: kerchunk
  version: 0.2.6
  top-level:
    - kerchunk
source:
  url: https://files.pythonhosted.org/packages/1f/c4/5e991922cd88cbc60749107a58e820534761d81046bcf3ef7d76ff1e24d5/kerchunk-0.2.6.tar.gz
  sha256: 7cb2a7a688ee39cfe45ffee1e9c7152201b408a9fbdc02c6fe08cbf2bdb0e281
  patches:
    - patches/0001-grib-scan-empty-coo-array.patch
requirements:
  run:
    - fsspec
    - numcodecs
    - numpy
    - ujson
    - zarr
    - cftime
    - xarray
    - h5py
    - cfgrib
    - scipy
about:
  home: https://github.com/fsspec/kerchunk
  PyPI: https://pypi.org/project/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
