package:
  name: appdirs
  version: 1.4.4
  top-level:
    - appdirs
source:
  url: https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
  sha256: a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128
about:
  home: http://github.com/ActiveState/appdirs
  PyPI: https://pypi.org/project/appdirs
  summary:
    A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
  license: MIT
