package:
  name: cmocean
  version: 4.0.3
  top-level:
    - cmocean
source:
  url: https://files.pythonhosted.org/packages/86/7b/97754548e9da3d41d7334e375b2cd712e9406a3f48823a5f0a166f42d63d/cmocean-4.0.3-py3-none-any.whl
  sha256: f2fc1d5e349db122ee0c9eac80bba969aa92dd2806548fce58dc8bef962f309e
requirements:
  run:
    - matplotlib
    - numpy
    - packaging
about:
  home: https://github.com/matplotlib/cmocean
  PyPI: https://pypi.org/project/cmocean
  summary: Colormaps for Oceanography
  license: MIT
