package:
  name: galpy
  version: 1.10.0
  top-level:
    - galpy
source:
  url: https://files.pythonhosted.org/packages/e4/a9/b8752eb6fff1131234e5f96a94a347734d990a85d69954c389c675dc047c/galpy-1.10.0.tar.gz
  sha256: ec046a4671b85e69de16d34e985583008ee85be609c8bc9555a59aa2f2382315
build:
  script:
    export LIBGSL_INCLUDE_PATH=$(pkg-config --cflags-only-I --dont-define-prefix
    gsl) export LIBGSL_LIBRARY_PATH=$(pkg-config --libs-only-L --dont-define-prefix
    gsl)
  cflags: |
    $(LIBGSL_INCLUDE_PATH)
  ldflags: |
    $(LIBGSL_LIBRARY_PATH)
  exports: requested
requirements:
  run:
    - numpy
    - scipy
    - matplotlib
    - astropy
    - future
    - setuptools
  host:
    - libgsl
    - numpy
    - scipy
test:
  imports:
    - galpy
    - galpy.potential
    - galpy.orbit
    - galpy.actionAngle
    - galpy.df
about:
  home: http://github.com/jobovy/galpy
  PyPI: https://pypi.org/project/galpy
  summary: Galactic Dynamics in python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - jobovy
