package:
  name: ipywidgets
  version: 8.1.5
  top-level:
    - ipywidgets
source:
  url: https://files.pythonhosted.org/packages/22/2d/9c0b76f2f9cc0ebede1b9371b6f317243028ed60b90705863d493bae622e/ipywidgets-8.1.5-py3-none-any.whl
  sha256: 3290f526f87ae6e77655555baba4f36681c555b8bdbbff430b70e52c34c86245
requirements:
  run:
    - comm                # required
    - ipython             # required
    - jupyterlab_widgets  # required, not loaded immediately
    - traitlets           # required
    - widgetsnbextension  # required, not loaded immediately
about:
  home: http://jupyter.org
  PyPI: https://pypi.org/project/ipywidgets
  summary: Jupyter interactive widgets
  license: BSD 3-Clause License
