package:
  name: ipywidgets
  version: 8.0.6
  top-level:
    - ipywidgets
source:
  url: https://files.pythonhosted.org/packages/50/7d/2c8b7bba2b1c2b5d1299f22fa7853f09b573c84e63b62870c13a6ec11990/ipywidgets-8.0.6-py3-none-any.whl
  sha256: a60bf8d2528997e05ac83fd19ea2fbe65f2e79fbe1b2b35779bdfc46c2941dcc
requirements:
  run:
    - widgetsnbextension
    - jupyterlab_widgets
about:
  home: http://jupyter.org
  PyPI: https://pypi.org/project/ipywidgets
  summary: Jupyter interactive widgets
  license: BSD 3-Clause License
