package:
  name: earthkit-time
  version: 0.1.6
  top-level:
    - earthkit.time
source:
  url: https://files.pythonhosted.org/packages/99/88/cb4ef756025e772fd5964920fdee450fbc377fce3271197d499de6cc8b7e/earthkit_time-0.1.6-py3-none-any.whl
  sha256: 5d60729d03b505730b8e7f62c6fd325182ae2e8d2b811e48172f16fedcbf0136
requirements:
  run:
    - pyyaml  # required
about:
  home: https://github.com/ecmwf/earthkit-time
  PyPI: https://pypi.org/project/earthkit-time
  summary: Date and time manipulation routines for the use of weather data
  license: Apache License 2.0
