package:
  name: flexparser
  version: "0.4"
  top-level:
    - flexparser
source:
  url: https://files.pythonhosted.org/packages/fe/5e/3be305568fe5f34448807976dc82fc151d76c3e0e03958f34770286278c1/flexparser-0.4-py3-none-any.whl
  sha256: 3738b456192dcb3e15620f324c447721023c0293f6af9955b481e91d00179846
requirements:
  run:
    - typing_extensions
about:
  home: https://github.com/hgrecco/flexparser
  PyPI: https://pypi.org/project/flexparser
  summary: Parsing made fun ... using typing.
  license: BSD-3-Clause
