package:
  name: numcodecs-wasm
  version: 0.1.2
  tag:
    - rust
  top-level:
    - numcodecs_wasm
source:
  url: https://files.pythonhosted.org/packages/source/n/numcodecs_wasm/numcodecs_wasm-0.1.2.tar.gz
  sha256: f7989af42f5781417c55be2a9de7296b47e504a2e8eb549ff9399153cb1580ad
about:
  home: https://github.com/juntyr/numcodecs-rs
  PyPI: https://pypi.org/project/numcodecs-wasm
  summary: numcodecs compression for codecs compiled to WebAssembly
  license: MPL-2.0
