package:
  name: yarl
  version: 1.16.0
  top-level:
    - yarl
source:
  url: https://files.pythonhosted.org/packages/23/52/e9766cc6c2eab7dd1e9749c52c9879317500b46fb97d4105223f86679f93/yarl-1.16.0.tar.gz
  sha256: b6f687ced5510a9a2474bbae96a4352e5ace5fa34dc44a217b0537fec1db00b4
requirements:
  run:
    - multidict
    - idna
about:
  home: https://github.com/aio-libs/yarl/
  PyPI: https://pypi.org/project/yarl
  summary: Yet another URL library
  license: Apache-2.0
