package:
  name: blosc2
  version: 3.2.1
  top-level:
    - blosc2
source:
  url: https://files.pythonhosted.org/packages/source/b/blosc2/blosc2-3.2.1.tar.gz
  sha256: bc10cc55e6ffa1984b2502e7c4a577064cf84a935602a5879e2685124bbb6141
build:
  backend-flags: |
    skbuild.cmake.define.WITH_OPTIM=OFF

requirements:
  host:
    # Dependencies that are needed to build the package
    - numpy
  run:
    # Dependencies that are needed to run the package
    - numpy
    - msgpack
    - ndindex

about:
  home: https://github.com/Blosc/python-blosc2
  PyPI: https://pypi.org/project/blosc2
  summary: A fast & compressed ndarray library with a flexible compute engine.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - FrancescAlted
