package:
  name: blosc2
  version: 3.3.1
  top-level:
    - blosc2
source:
  url: https://files.pythonhosted.org/packages/source/b/blosc2/blosc2-3.3.1.tar.gz
  sha256: 96cb4ef5279812d689ed85ae15134524eca35fecdfa945e68d3ec13a3319c662
build:
  backend-flags: |
    skbuild.cmake.define.WITH_OPTIM=OFF

requirements:
  host:
    # Dependencies that are needed to build the package
    - numpy
  run:
    # Dependencies that are needed to run the package
    - numpy
    - msgpack
    - ndindex

about:
  home: https://github.com/Blosc/python-blosc2
  PyPI: https://pypi.org/project/blosc2
  summary: A fast & compressed ndarray library with a flexible compute engine.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - FrancescAlted
