package:
  name: proplot
  version: 0.9.7
  top-level:
    - proplot
source:
  url: https://files.pythonhosted.org/packages/af/cd/419a7137fe163614414bc8e9abdb1cd12baa12a80dc6930ed3bc60d19c2d/proplot-0.9.7-py3-none-any.whl
  sha256: e2732cbf7520505a3bb399ef75d762d9645813bc2208deefe7ca2d5c8e4f6fa1
requirements:
  run:
    - matplotlib
    - numpy
    - setuptools
about:
  home: https://proplot.readthedocs.io
  PyPI: https://pypi.org/project/proplot
  summary:
    A succinct matplotlib wrapper for making beautiful, publication-quality
    graphics.
  license: MIT
