package:
  name: earthkit-regrid
  version: 0.3.2
  top-level:
    - earthkit.regrid
source:
  url: https://files.pythonhosted.org/packages/4f/d6/14f38b97805ea35fd6b98144575b8f1d9124dda0e3ec346707aefcf052e9/earthkit_regrid-0.3.2.tar.gz
  sha256: c9d838d322fc15e3a801364d55a69e582d1d1bf32a575472a2f9abbb5a95cd47
  patches:
    - patches/0001-no-caching.patch
requirements:
  run:
    - multiurl
    - filelock
    - scipy
about:
  home: https://github.com/ecmwf/earthkit-regrid
  PyPI: https://pypi.org/project/earthkit-regrid
  summary: ECMWF python regridding toolkit
  license: Apache License 2.0
