package:
  name: eckitlib
  version: 1.28.5

source:
  url: https://github.com/ecmwf/eckit/archive/refs/tags/1.28.5.tar.gz
  sha256: e856651a2a532af6a37c69e8e53eb805beaad1f452007930e479e94c56401dc0
  patches:
    - patches/0001-uid_t.patch
    - patches/0002-strerror_r.patch
    - patches/0003-no-tools.patch
    - patches/0004-no-regressions.patch
    - patches/0005-system-info.patch
    - patches/0006-library-path.patch
  extras:
    - [extras/__init__.py, __init__.py]
    - [extras/pyproject.toml, pyproject.toml]

build:
  script: |
    mkdir -p src/eckitlib
    mv __init__.py src/eckitlib

    git clone --branch 3.7.0 --depth 1 https://github.com/ecmwf/ecbuild;

    mkdir -p build;

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=ON \
        -DENABLE_BUILD_TOOLS=OFF \
        -DENABLE_MPI=OFF \
        -DENABLE_ECKIT_CMD=OFF \
        -DENABLE_ECKIT_SQL=ON \
        -DENABLE_OMP=OFF \
        -DENABLE_ECKIT_CODEC=OFF \
        -DDISABLE_OS_CHECK=ON \
        -DENABLE_TESTS=OFF;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;
  post: |
    rm -f *.so
    rm -rf pkgconfig
    rm -rf sandbox
    mkdir -p eckitlib/include
    cp -rP ${WASM_LIBRARY_DIR}/include/eckit eckitlib/include
    mkdir -p eckitlib/lib
    cp -rP ${WASM_LIBRARY_DIR}/lib/libeckit.so eckitlib/lib
    mkdir -p eckitlib.libs
    cp -rP ${WASM_LIBRARY_DIR}/lib/libeckit*.so eckitlib.libs
    rm -f eckitlib.libs/libeckit.so
    mkdir -p eckitlib/lib/cmake
    cp -rP ${WASM_LIBRARY_DIR}/lib/cmake/eckit eckitlib/lib/cmake
    mkdir -p eckitlib/lib/pkgconfig
    cp -rP ${WASM_LIBRARY_DIR}/lib/pkgconfig/eckit*.pc eckitlib/lib/pkgconfig
    mkdir -p eckitlib/share
    cp -rP ${WASM_LIBRARY_DIR}/etc/eckit eckitlib/share
