package:
  name: pdbufr
  version: 0.11.0
  top-level:
    - pdbufr
source:
  url: https://files.pythonhosted.org/packages/17/ac/2f955e67be411362129d435545f8e66f2ebdc2c51da634837e7830986f18/pdbufr-0.11.0.tar.gz
  sha256: a9ea85e29cad5c66a0573f28ac21874df37859516458b311b5e3398bbc8e9c78
requirements:
  run:
    - attrs
    - eccodes
    - pandas
about:
  home: https://github.com/ecmwf/pdbufr
  PyPI: https://pypi.org/project/pdbufr
  summary: Pandas reader for the BUFR format using ecCodes.
  license: Apache License Version 2.0
