[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyterlite-preload"
version = "0.0.0"

dependencies = [
    "ipyloglite == 0.0.0",
    "pyodide-http == 0.2.1",
]
