package:
  name: wrapt
  version: 1.17.2
  top-level:
    - wrapt
source:
  url: https://files.pythonhosted.org/packages/source/w/wrapt/wrapt-1.17.2.tar.gz
  sha256: 41388e9d4d1522446fe79d3213196bd9e3b301a336965b9e27ca2788ebd122f3
about:
  home: https://github.com/GrahamDumpleton/wrapt
  PyPI: https://pypi.org/project/wrapt
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD-2-Clause
