package:
  name: cads-api-client
  version: 1.3.0
  top-level:
    - cads_api_client
source:
  url: https://files.pythonhosted.org/packages/fc/e5/33922dadc2f241ffb1878211df992776c949f027885caeb23fd804a442a5/cads_api_client-1.3.0-py3-none-any.whl
  sha256: e6934046e63f6f1cdf3be77cdd48f4085a5b485aa45b35ce499912de6ddf9188
requirements:
  run:
    - attrs
    - multiurl
    - requests
    - typing-extensions
about:
  home: https://github.com/ecmwf-projects/cads-api-client
  PyPI: https://pypi.org/project/cads-api-client
  summary: CADS API Python client
  license: Apache 2.0
