package:
  name: cads-api-client
  version: 1.4.7
  top-level:
    - cads_api_client
source:
  url: https://files.pythonhosted.org/packages/2c/a3/a07a73dc272a7950db2bb769684f103cb440ef36efeb43f305d49abc1af2/cads_api_client-1.4.7-py3-none-any.whl
  sha256: a0b59908eba7d2f029a384ff7ec94014552333ea47169d067f650686d2c75c19
requirements:
  run:
    - attrs
    - multiurl
    - requests
    - typing-extensions
about:
  home: https://github.com/ecmwf-projects/cads-api-client
  PyPI: https://pypi.org/project/cads-api-client
  summary: CADS API Python client
  license: Apache 2.0
