package:
  name: cads-api-client
  version: 1.5.4
  top-level:
    - cads_api_client
source:
  url: https://files.pythonhosted.org/packages/59/2a/30210f8b55d14247c698d53a90c6707b540aa76022342777ef0a18660a19/cads_api_client-1.5.4-py3-none-any.whl
  sha256: fe557f5ef726b34c5cb4aa2c73379ac207c521b25bb08069806cc0519278a488
requirements:
  run:
    - attrs
    - multiurl
    - requests
    - typing-extensions
about:
  home: https://github.com/ecmwf-projects/cads-api-client
  PyPI: https://pypi.org/project/cads-api-client
  summary: CADS API Python client
  license: Apache 2.0
