package:
  name: polytope-client
  version: 0.7.4
  top-level:
    - polytope
source:
  url: https://files.pythonhosted.org/packages/c6/75/e3fd211c9b273df86ff387b989c794b6bd44ddc01dd00c720a18bfd01cde/polytope_client-0.7.4-py3-none-any.whl
  sha256: fc038b41c6e0c6ad11efc8953f58e6399ef65e66dfa3953edfbb84510f49a823
requirements:
  run:
    - click
    - requests
    - pyyaml
    - jsonschema
    - docstring_parser
    - tqdm
about:
  home: https://github.com/ecmwf-projects/polytope-client
  PyPI: https://pypi.org/project/polytope-client
  summary: A Python and command-line client to communicate with a Polytope API server.
  license: Apache License 2.0
