package:
  name: aiobotocore
  version: 2.15.2
  top-level:
    - aiobotocore
source:
  url: https://files.pythonhosted.org/packages/a4/57/6402242dde160d9ef9903487b4277443dc3da04615f6c4d3b48564a8ab57/aiobotocore-2.15.2-py3-none-any.whl
  sha256: d4d3128b4b558e2b4c369bfa963b022d7e87303adb82eec623cec8aa77ae578a
requirements:
  run:
    - botocore
    - aiohttp
    - wrapt
    - aioitertools
about:
  home: https://github.com/aio-libs/aiobotocore
  PyPI: https://pypi.org/project/aiobotocore
  summary: Async client for aws services using botocore and aiohttp
  license: Apache License 2.0
