package:
  name: ecmwf-api-client
  version: 1.6.3
  top-level:
    - ecmwfapi
source:
  url: https://files.pythonhosted.org/packages/5b/44/ddeb18174b1cce4fe2c714c1968cd0e4272c6869c5073a3b270f071e5549/ecmwf-api-client-1.6.3.tar.gz
  sha256: 3a00bda34a72e2d5198c97399a4750b42a6633efdb5e1b3a5fd2b2bbaa5db0d6
about:
  home: https://github.com/ecmwf/ecmwf-api-client
  PyPI: https://pypi.org/project/ecmwf-api-client
  summary: Python client for ECMWF web services API.
  license: Apache License Version 2.0
