package:
  name: aiohttp
  version: 3.11.16
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.11.16.tar.gz
  sha256: 16f8a2c9538c14a557b4d309ed4d0a7c60f0253e8ed7b6c9a2859a7582f8b1b8
  patches:
    - patches/0001-pyodide-connection.patch
    - patches/0002-export-http-exceptions.patch
    - patches/0003-requires-jupyterlite-cors.patch

requirements:
  run:
    - frozenlist
    - jupyterlite-cors

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
