package:
  name: aiohttp
  version: 3.9.5
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/04/a4/e3679773ea7eb5b37a2c998e25b017cc5349edf6ba2739d1f32855cfb11b/aiohttp-3.9.5.tar.gz
  sha256: edea7d15772ceeb29db4aff55e482d4bcfb6ae160ce144f2682de02f6d693551
  patches:
    - patches/0001-pyodide-connection.patch

requirements:
  run:
    - aiosignal
    - async-timeout
    - attrs
    - charset-normalizer
    - frozenlist
    - jupyterlite-cors
    - multidict
    - yarl

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
