package:
  name: aiohttp
  version: 3.11.10
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/94/c4/3b5a937b16f6c2a0ada842a9066aad0b7a5708427d4a202a07bf09c67cbb/aiohttp-3.11.10.tar.gz
  sha256: b1fc6b45010a8d0ff9e88f9f2418c6fd408c99c211257334aff41597ebece42e
  patches:
    - patches/0001-pyodide-connection.patch
    - patches/0002-export-http-exceptions.patch

requirements:
  run:
    - aiohappyeyeballs
    - aiosignal
    - async-timeout
    - attrs
    - charset-normalizer
    - frozenlist
    - jupyterlite-cors
    - multidict
    - propcache
    - yarl

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
