package:
  name: aiohttp
  version: 3.11.14
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.11.14.tar.gz
  sha256: d6edc538c7480fa0a3b2bdd705f8010062d74700198da55d16498e1b49549b9c
  patches:
    - patches/0001-pyodide-connection.patch
    - patches/0002-export-http-exceptions.patch
    - patches/0003-requires-jupyterlite-cors.patch

requirements:
  run:
    - frozenlist
    - jupyterlite-cors

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
