package:
  name: ipdb
  version: 0.13.13
  top-level:
    - ipdb
source:
  url: https://files.pythonhosted.org/packages/0c/4c/b075da0092003d9a55cf2ecc1cae9384a1ca4f650d51b00fc59875fe76f6/ipdb-0.13.13-py3-none-any.whl
  sha256: 45529994741c4ab6d2388bfa5d7b725c2cf7fe9deffabdb8a6113aa5ed449ed4
requirements:
  run:
    - ipython
    - decorator
about:
  home: https://github.com/gotcha/ipdb
  PyPI: https://pypi.org/project/ipdb
  summary: IPython-enabled pdb
  license: BSD
