package:
  name: attrs
  version: 24.2.0
  top-level:
    - attr
    - attrs
source:
  sha256: 81921eb96de3191c8258c199618104dd27ac608d9366f5e35d011eae1867ede2
  url: https://files.pythonhosted.org/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl
requirements:
  run:
    - six
about:
  home: https://www.attrs.org/
  PyPI: https://pypi.org/project/attrs
  summary: Classes Without Boilerplate
  license: MIT
