package:
  name: covjson-pydantic
  version: 0.5.0
  top-level:
    - covjson_pydantic
source:
  url: https://files.pythonhosted.org/packages/6f/46/900c01abffed3e94a0311bf961413da254a2c8b254fff1f34e8bd3cdf014/covjson_pydantic-0.5.0-py3-none-any.whl
  sha256: 5330e218f86aaef1c1aa372c7a88376d5b9464a6617239d8cb31bb2c1fcad20d
requirements:
  run:
    - pydantic
about:
  home: https://github.com/knmi/covjson-pydantic
  PyPI: https://pypi.org/project/covjson-pydantic
  summary: The Pydantic models for CoverageJSON
  license: Apache License Version 2.0
