package:
  name: packaging
  version: "23.2"
  top-level:
    - packaging
source:
  sha256: 8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7
  url: https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl

about:
  home: https://github.com/pypa/packaging
  PyPI: https://pypi.org/project/packaging
  summary: Core utilities for Python packages
  license: BSD-2-Clause or Apache-2.0
