package:
  name: packaging
  version: "25.0"
  top-level:
    - packaging
source:
  sha256: d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f
  url: https://files.pythonhosted.org/packages/source/p/packaging/packaging-25.0.tar.gz
  patches:
    - patches/0001-Add-Pyodide-compatibility.patch

about:
  home: https://github.com/pypa/packaging
  PyPI: https://pypi.org/project/packaging
  summary: Core utilities for Python packages
  license: BSD-2-Clause or Apache-2.0
