package:
  name: filelock
  version: 3.17.0
  top-level:
    - filelock
source:
  url: https://files.pythonhosted.org/packages/source/f/filelock/filelock-3.17.0.tar.gz
  sha256: ee4e77401ef576ebb38cd7f13b9b28893194acc20a8e68e18730ba9c0e54660e
  patches:
    - patches/0001-fcntl-lock-check.patch
about:
  home: https://github.com/tox-dev/filelock
  PyPI: https://pypi.org/project/filelock
  summary: A platform independent file lock.
  license: The Unlicense
