package:
  name: filelock
  version: 3.16.1
  top-level:
    - filelock
source:
  url: https://files.pythonhosted.org/packages/9d/db/3ef5bb276dae18d6ec2124224403d1d67bccdbefc17af4cc8f553e341ab1/filelock-3.16.1.tar.gz
  sha256: c249fbfcd5db47e5e2d6d62198e565475ee65e4831e2561c8e313fa7eb961435
  patches:
    - patches/0001-fcntl-lock-check.patch
about:
  home: https://github.com/tox-dev/filelock
  PyPI: https://pypi.org/project/filelock
  summary: A platform independent file lock.
  license: The Unlicense
