package:
  name: filelock
  version: 3.13.4
  top-level:
    - filelock
source:
  url: https://files.pythonhosted.org/packages/38/ff/877f1dbe369a2b9920e2ada3c9ab81cf6fe8fa2dce45f40cad510ef2df62/filelock-3.13.4.tar.gz
  sha256: d13f466618bfde72bd2c18255e269f72542c6e70e7bac83a0232d6b1cc5c8cf4
  patches:
    - patches/0001-fcntl-lock-check.patch
about:
  home: https://github.com/tox-dev/filelock
  PyPI: https://pypi.org/project/filelock
  summary: A platform independent file lock.
  license: The Unlicense
