package:
  name: adjustText
  version: 1.3.0
  top-level:
    - adjustText
source:
  url: https://files.pythonhosted.org/packages/53/1c/8feedd607cc14c5df9aef74fe3af9a99bf660743b842a9b5b1865326b4aa/adjustText-1.3.0-py3-none-any.whl
  sha256: da23d7b24b6db5ffa039bb136bfa556207365e32f48ac74b07ad26dd485bc691
requirements:
  run:
    - numpy
    - matplotlib
    - scipy
about:
  home: https://github.com/Phlya/adjustText
  PyPI: https://pypi.org/project/adjustText
  summary: Iteratively adjust text position in matplotlib plots to minimize overlaps
  license: MIT
