package:
  name: adjustText
  version: 1.2.0
  top-level:
    - adjustText
source:
  url: https://files.pythonhosted.org/packages/71/0d/baaa8e9f8c14e33f353419f7c7da4c270145626f043e98740e743ece6a8e/adjustText-1.2.0-py3-none-any.whl
  sha256: 53212d5ea02b224ba56a1929d30264c8f6ea35d18a39f0fc351cff0bca66a214
requirements:
  run:
    - numpy
    - matplotlib
    - scipy
about:
  home: https://github.com/Phlya/adjustText
  PyPI: https://pypi.org/project/adjustText
  summary: Iteratively adjust text position in matplotlib plots to minimize overlaps
  license: MIT
