package:
  name: eccodes
  version: 2.40.0
  top-level:
    - eccodes
    - gribapi
source:
  url: https://github.com/ecmwf/eccodes-python/archive/refs/tags/2.40.0.tar.gz
  sha256: d983e06bd6607b8d8b7d633879917854196cd584a46fcec1fd1d1577b88159ed
  patches:
    - patches/0001-package-shared-library.patch
requirements:
  run:
    - cffi
    - findlibs
    - numpy
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
