package:
  name: eccodes
  version: 2.40.1
  top-level:
    - eccodes
    - gribapi
source:
  url: https://files.pythonhosted.org/packages/source/e/eccodes/eccodes-2.40.1.tar.gz
  sha256: 9e0dee65a464bdd131077375dc482841385d9eaef7b5194bf2e5697279ef5d7c
  patches:
    - patches/0001-package-shared-library.patch
requirements:
  run:
    - cffi
    - findlibs
    - numpy
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
