package:
  name: eccodes
  version: 2.38.3
  top-level:
    - eccodes
    - gribapi
source:
  url: https://github.com/ecmwf/eccodes-python/archive/refs/tags/2.38.3.tar.gz
  sha256: 59868edb2b7c8afbf0784780f12761e44f686a7e5e8e2fb2bb7ad9772b7d53b5
  patches:
    - patches/0001-package-shared-library.patch
requirements:
  run:
    - attrs
    - cffi
    - findlibs
    - numpy
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
