package:
  name: eccodes
  version: 2.38.3
  top-level:
    - eccodes
    - gribapi
source:
  url: https://files.pythonhosted.org/packages/38/20/1228499507b9e08eae0604cc9ec5598a84a873aeaebeb4855710eb81c771/eccodes-2.38.3.tar.gz
  sha256: 8dc76ab217199761dd6f93aee65eadf3a1e9f5760fee488f9f0643463ee8bc78
requirements:
  run:
    - attrs
    - cffi
    - findlibs
    - numpy
  host:
    - libeccodes
build:
  vendor-sharedlib: true
  script: |
    cp ${WASM_LIBRARY_DIR}/lib/libeccodes.so eccodes/copying/
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
