package:
  name: eccodeslib
  version: 2.40.0

source:
  url: https://github.com/ecmwf/eccodes/archive/refs/tags/2.40.0.tar.gz
  sha256: 91590147c623a3ca08a81da0f4925fd68ba29b9a0a7d5d862048543da2a0c56a
  patches:
    - patches/0001-32bit-support-hack.patch
  extras:
    - [extras/__init__.py, __init__.py]
    - [extras/pyproject.toml, pyproject.toml]

requirements:
  host:
    - libaec

build:
  type: package
  script: |
    mkdir -p src/eccodeslib
    mv __init__.py src/eccodeslib

    git clone --branch 3.7.0 --depth 1 https://github.com/ecmwf/ecbuild;

    mkdir -p build;

    export EMSCRIPTEN_SYSROOT=$(em-config CACHE)/sysroot
    export EMSCRIPTEN_INCLUDE=$EMSCRIPTEN_SYSROOT/include
    export EMSCRIPTEN_BIN=$EMSCRIPTEN_SYSROOT/bin
    export EMSCRIPTEN_LIB=$EMSCRIPTEN_SYSROOT/lib/wasm32-emscripten/pic

    embuilder build libjpeg --pic
    embuilder build libpng-wasm-sjlj --pic

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=ON \
        -DENABLE_NETCDF=OFF \
        -DENABLE_JPG=ON \
        -DENABLE_JPG_LIBOPENJPEG=OFF \
        -DENABLE_JPG_LIBJASPER=OFF \
        -DENABLE_PNG=OFF \
        -DENABLE_AEC=ON \
        -DENABLE_FORTRAN=OFF \
        -DENABLE_MEMFS=ON \
        -DDISABLE_OS_CHECK=ON \
        -DENABLE_TESTS=OFF \
        -DENABLE_PRODUCT_GRIB=ON \
        -DENABLE_PRODUCT_BUFR=ON \
        -DENABLE_EXAMPLES=OFF \
        -DENABLE_BUILD_TOOLS=OFF \
        -DENABLE_INSTALL_ECCODES_DEFINITIONS=ON \
        -DENABLE_INSTALL_ECCODES_SAMPLES=OFF;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;
  post: |
    rm -f libeccodes.so
    rm -f libeccodes_memfs.so
    rm -rf pkgconfig
    mkdir -p eccodeslib/include
    cp -P ${WASM_LIBRARY_DIR}/include/eccodes*.h eccodeslib/include
    cp -P ${WASM_LIBRARY_DIR}/include/grib_api.h eccodeslib/include
    mkdir -p eccodeslib/lib
    cp -rP ${WASM_LIBRARY_DIR}/lib/libeccodes.so eccodeslib/lib
    mkdir -p eccodeslib.libs
    cp -rP ${WASM_LIBRARY_DIR}/lib/libeccodes_memfs.so eccodeslib.libs
    mkdir -p eccodeslib/lib/cmake
    cp -rP ${WASM_LIBRARY_DIR}/lib/cmake/eccodes eccodeslib/lib/cmake
    mkdir -p eccodeslib/lib/pkgconfig
    cp -rP ${WASM_LIBRARY_DIR}/lib/pkgconfig/eccodes.pc eccodeslib/lib/pkgconfig
    mkdir -p eccodeslib/share
    cp -rP ${WASM_LIBRARY_DIR}/share/eccodes eccodeslib/share
