package:
  name: jupyterlab_widgets
  version: 3.0.13
  top-level:
    - jupyterlab_widgets
source:
  url: https://files.pythonhosted.org/packages/a9/93/858e87edc634d628e5d752ba944c2833133a28fa87bb093e6832ced36a3e/jupyterlab_widgets-3.0.13-py3-none-any.whl
  sha256: e3cda2c233ce144192f1e29914ad522b2f4c40e77214b0cc97377ca3d323db54
about:
  home: https://github.com/jupyter-widgets/ipywidgets
  PyPI: https://pypi.org/project/jupyterlab_widgets
  summary: Jupyter interactive widgets for JupyterLab
  license: BSD-3-Clause
