package:
  name: jupyterlab_widgets
  version: 3.0.7
  top-level:
    - jupyterlab_widgets
source:
  url: https://files.pythonhosted.org/packages/46/98/e7ce879b7b5d4871b80e291be967d22e5e66fa43474c476a95fe6231f50d/jupyterlab_widgets-3.0.7-py3-none-any.whl
  sha256: c73f8370338ec19f1bec47254752d6505b03601cbd5a67e6a0b184532f73a459
about:
  home: https://github.com/jupyter-widgets/ipywidgets
  PyPI: https://pypi.org/project/jupyterlab_widgets
  summary: Jupyter interactive widgets for JupyterLab
  license: BSD-3-Clause
