package:
  name: s3fs
  version: 2024.12.0
  top-level:
    - s3fs
source:
  url: https://files.pythonhosted.org/packages/f7/af/eaec1466887348d7f6cc9d3a668b30b62a4629fb187d0268146118ba3d5e/s3fs-2024.12.0-py3-none-any.whl
  sha256: d8665549f9d1de083151582437a2f10d5f3b3227c1f8e67a2b0b730db813e005
requirements:
  run:
    - aiobotocore
    - fsspec
    - aiohttp
about:
  home: http://github.com/fsspec/s3fs/
  PyPI: https://pypi.org/project/s3fs
  summary: Convenient Filesystem interface over S3
  license: BSD
