package:
  name: s3fs
  version: 2024.10.0
  top-level:
    - s3fs
source:
  url: https://files.pythonhosted.org/packages/99/44/bb9ff095ae7b1b6908480f683b6ca6b71c2105d343a5e5cb25334b01f5fa/s3fs-2024.10.0-py3-none-any.whl
  sha256: 7a2025d60d5b1a6025726b3a5e292a8e5aa713abc3b16fd1f81735181f7bb282
requirements:
  run:
    - aiobotocore
    - fsspec
    - aiohttp # FIXME: requires >=3.9.2
about:
  home: http://github.com/fsspec/s3fs/
  PyPI: https://pypi.org/project/s3fs
  summary: Convenient Filesystem interface over S3
  license: BSD
