package:
  name: Jinja2
  version: 3.1.4
  tag:
    - core
    - min-scipy-stack
  top-level:
    - jinja2
requirements:
  run:
    - MarkupSafe
source:
  sha256: bc5dd2abb727a5319567b7a813e6a2e7318c39f4f487cfe6c89c6f9c7d25197d
  url: https://files.pythonhosted.org/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl
about:
  home: https://palletsprojects.com/p/jinja/
  PyPI: https://pypi.org/project/Jinja2
  summary: A very fast and expressive template engine.
  license: BSD-3-Clause
