package:
  name: ipyfilite
  version: 0.1.30
  top-level:
    - ipyfilite
source:
  url: https://files.pythonhosted.org/packages/39/e2/c37b62120f17f60c222f37456001b5a075d7aedefaa391846787ed496ced/ipyfilite-0.1.30-py3-none-any.whl
  sha256: 18bcddf421a1dda62e6b375c25d42baf79c8951d940b90b230fa6b7000d0bde1
requirements:
  run:
    - ipywidgets
about:
  home: https://github.com/juntyr/ipyfilite
  PyPI: https://pypi.org/project/ipyfilite
  summary:
    File upload widget specifically for Pyodide kernels running in JupyterLite.
    Uploaded files are not loaded into memory but mounted as read-only files in a
    new WORKERFS.
  license: BSD 3-Clause License
