package:
  name: ipyfilite
  version: 0.1.27
  top-level:
    - ipyfilite
source:
  url: https://files.pythonhosted.org/packages/9e/6d/6fbfe3cf613507188327710775ef193312869c348d7c2001407eff67b712/ipyfilite-0.1.27-py3-none-any.whl
  sha256: d12a003a0e366fabeb236e7b7e9beefe7051a962d617cded60f59e445a88a35c
requirements:
  run:
    - ipywidgets
about:
  home: https://github.com/juntyr/ipyfilite
  PyPI: https://pypi.org/project/ipyfilite
  summary:
    File upload widget specifically for Pyodide kernels running in JupyterLite.
    Uploaded files are not loaded into memory but mounted as read-only files in a
    new WORKERFS.
  license: BSD 3-Clause License
