package:
  name: pooch
  version: 1.8.1
  top-level:
    - pooch
source:
  url: https://files.pythonhosted.org/packages/f4/72/8ae0f1ba4ce6a4f6d4d01a60a9fdf690fde188c45c1872b0b4ddb0607ace/pooch-1.8.1-py3-none-any.whl
  sha256: 6b56611ac320c239faece1ac51a60b25796792599ce5c0b1bb87bf01df55e0a9
requirements:
  run:
    - lzma
    - platformdirs
    - packaging
    - requests
about:
  home: https://github.com/fatiando/pooch
  PyPI: https://pypi.org/project/pooch
  summary:
    "Pooch manages your Python library's sample data files: it automatically\
    \ downloads and stores them in a local directory, with support for versioning\
    \ and corruption checks."
  license: BSD 3-Clause License
