package:
  name: libexpat
  version: 2.6.3

source:
  url: https://github.com/libexpat/libexpat/releases/download/R_2_6_3/expat-2.6.3.tar.bz2
  sha256: b8baef92f328eebcf731f4d18103951c61fa8c8ec21d5ff4202fb6f2198aeb2d

build:
  type: static_library
  script: |
    mkdir -p build;

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=off \
        -DEXPAT_BUILD_EXAMPLES=off \
        -DEXPAT_BUILD_TESTS=off \
        -DEXPAT_BUILD_TOOLS=off \
        -DEXPAT_BUILD_FUZZERS=off \
        -DEXPAT_BUILD_DOCS=off;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libexpat.a ${DISTDIR}
