package:
  name: gribscan
  version: 0.0.13
  top-level:
    - gribscan
source:
  url: https://files.pythonhosted.org/packages/75/81/15135410fdd62d79476056842d4279e67b4fbec88deb3a37d21c6d7e27c0/gribscan-0.0.13.tar.gz
  sha256: eea3502a26dd8789606788a0e1be94a8601bde32773c0fa565f155c9b4e2fd23
  patches:
    - patches/0001-no-aeccodec.patch
requirements:
  run:
    - cfgrib
    - eccodes
    - numcodecs
    - numpy
    - scipy
about:
  home: https://github.com/gribscan/gribscan
  PyPI: https://pypi.org/project/gribscan
  summary: Create indices for GRIB files and provide an xarray interface.
  license: MIT License
