package:
  name: rpds-py
  version: 0.24.0
  tag:
    - rust
  top-level:
    - rpds
source:
  url: https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-0.24.0.tar.gz
  sha256: 772cc1b2cd963e7e17e6cc55fe0371fb9c704d63e44cacec7b9b7f523b78919e
requirements:
  executable:
    - rustup
about:
  home: https://rpds.readthedocs.io
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
