package:
  name: rpds-py
  version: 0.23.1
  tag:
    - rust
  top-level:
    - rpds
source:
  url: https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-0.23.1.tar.gz
  sha256: 7f3240dcfa14d198dba24b8b9cb3b108c06b68d45b7babd9eefc1038fdf7e707
requirements:
  executable:
    - rustup
  constraint:
    - maturin < 1.8
about:
  home: https://rpds.readthedocs.io
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
