package:
  name: pandas
  version: 2.2.1
  tag:
    - min-scipy-stack
  top-level:
    - pandas
source:
  url: https://files.pythonhosted.org/packages/3d/59/2afa81b9fb300c90531803c0fd43ff4548074fa3e8d0f747ef63b3b5e77a/pandas-2.2.1.tar.gz
  sha256: 0ab90f87093c13f3e8fa45b48ba9f39181046e8f3317d3aadb2fffbb1b978572
build:
  cflags:
    -Werror=implicit-function-declaration -Werror=mismatched-parameter-types
    -Werror=mismatched-return-types -Oz
  ldflags: --Wl,--fatal-warnings -Oz
requirements:
  host:
    - numpy
  run:
    - numpy
    - python-dateutil
    - pytz
    - tzdata
about:
  home: https://pandas.pydata.org
  PyPI: https://pypi.org/project/pandas
  summary: Powerful data structures for data analysis, time series, and statistics
  license: BSD-3-Clause
