package:
  name: fsspec
  version: 2025.3.1
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/source/f/fsspec/fsspec-2025.3.1.tar.gz
  sha256: b3ec826bd18ed4ff0e5d172a8c6421ea5258e83d4f28369001369733d658a5f6
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
