package:
  name: fsspec
  version: 2024.10.0
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/a0/52/f16a068ebadae42526484c31f4398e62962504e5724a8ba5dc3409483df2/fsspec-2024.10.0.tar.gz
  sha256: eda2d8a4116d4f2429db8550f2457da57279247dd930bb12f821b58391359493
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
