package:
  name: fsspec
  version: 2025.3.2
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/source/f/fsspec/fsspec-2025.3.2.tar.gz
  sha256: e52c77ef398680bbd6a98c0e628fbc469491282981209907bbc8aea76a04fdc6
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
