package:
  name: Bottleneck
  version: 1.4.2
  top-level:
    - bottleneck
source:
  url: https://files.pythonhosted.org/packages/2e/61/9fb34409d58f04e1929da41666a055c36f9495903ff669b80c893bdee65f/bottleneck-1.4.2.tar.gz
  sha256: fa8e8e1799dea5483ce6669462660f9d9a95649f6f98a80d315b84ec89f449f4
requirements:
  host:
    - numpy
  run:
    - numpy
about:
  home: https://github.com/pydata/bottleneck
  PyPI: https://pypi.org/project/bottleneck
  summary: Fast NumPy array functions written in C
  license: Simplified BSD
