package:
  name: botocore
  version: 1.35.49
  top-level:
    - botocore
source:
  url: https://files.pythonhosted.org/packages/e3/3f/7c932ed4f6884b37e9a5bd3b37f88b35fa89491d635ab5b2cfeb8b800f95/botocore-1.35.49-py3-none-any.whl
  sha256: aed4d3643afd702920792b68fbe712a8c3847993820d1048cd238a6469354da1
requirements:
  run:
    - jmespath
    - python-dateutil
    - ssl
    - urllib3
about:
  home: https://github.com/boto/botocore
  PyPI: https://pypi.org/project/botocore
  summary: Low-level, data-driven core of boto 3.
  license: Apache License 2.0
