package:
  name: botocore
  version: 1.35.36
  top-level:
    - botocore
source:
  url: https://files.pythonhosted.org/packages/2a/60/056d58b606731f94fe395266c604ea9efcecc10e6857ceb9b10e6831d746/botocore-1.35.36-py3-none-any.whl
  sha256: 64241c778bf2dc863d93abab159e14024d97a926a5715056ef6411418cb9ead3
requirements:
  run:
    - jmespath
    - python-dateutil
    - ssl
    - urllib3
about:
  home: https://github.com/boto/botocore
  PyPI: https://pypi.org/project/botocore
  summary: Low-level, data-driven core of boto 3.
  license: Apache License 2.0
