package:
  name: fonttools
  version: 4.55.3
  top-level:
    - fontTools
source:
  url: https://files.pythonhosted.org/packages/99/3b/406d17b1f63e04a82aa621936e6e1c53a8c05458abd66300ac85ea7f9ae9/fonttools-4.55.3-py3-none-any.whl
  sha256: f412604ccbeee81b091b420272841e5ec5ef68967a9790e80bffd0e30b8e2977
about:
  home: http://github.com/fonttools/fonttools
  PyPI: https://pypi.org/project/fontTools
  summary: Tools to manipulate font files
  license: MIT
