package:
  name: earthkit-transforms
  version: 0.3.4.1
  top-level:
    - earthkit.transforms
source:
  url: https://files.pythonhosted.org/packages/4d/3d/89e54766e6bdc85a6d805f47aac317f5cb3e5f286b44e5178fb382fe5e9e/earthkit_transforms-0.3.4.1-py3-none-any.whl
  sha256: 76cdbee7e0143c889897596ef07d6b306bef35188e98425e8d9c32d0e0a5f84b
requirements:
  run:
    - earthkit-data  # required
    - geopandas      # required
    - numpy          # required
    - pandas         # required
    - rasterio       # required, not loaded immediately
    - xarray         # required
about:
  home: https://github.com/ecmwf/earthkit-transforms
  PyPI: https://pypi.org/project/earthkit-transforms
  summary: Aggregation tools for meteorological and climate data.
  license: Apache License Version 2.0
