package:
  name: pyparsing
  version: 3.2.0
  top-level:
    - pyparsing
source:
  sha256: 93d9577b88da0bbea8cc8334ee8b918ed014968fd2ec383e868fb8afb1ccef84
  url: https://files.pythonhosted.org/packages/be/ec/2eb3cd785efd67806c46c13a17339708ddc346cbb684eade7a6e6f79536a/pyparsing-3.2.0-py3-none-any.whl
about:
  home: https://github.com/pyparsing/pyparsing/
  license: MIT
