package:
  name: zarr
  version: 2.17.0
  top-level:
    - zarr
source:
  sha256: 6390a2b8af31babaab4c963efc45bf1da7f9500c9aafac193f84cf019a7c66b0
  url: https://files.pythonhosted.org/packages/f0/b9/ea61804312f289910b712ab8de5b9811ed9c2bc2f091a41f372644c149f8/zarr-2.17.0.tar.gz
requirements:
  run:
    - numpy
    - asciitree
    - numcodecs
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  license: MIT
