package:
  name: zarr
  version: 3.0.7
  top-level:
    - zarr
source:
  sha256: c06da406e08da9565ba368ac0337a4466d7743f643acac2873beee4458b6e5e1
  url: https://files.pythonhosted.org/packages/source/z/zarr/zarr-3.0.7.tar.gz
  patches:
    - patches/0001-syncify-awaitable.patch
requirements:
  run:
    - crc32c
    - numcodecs
    - numpy
    - packaging
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  license: MIT
