package:
  name: cf-units
  version: 3.2.0
  top-level:
    - cf_units
source:
  url: https://files.pythonhosted.org/packages/5a/f4/1d9aa224fe8f70034e9ea524d1dac511b0976bae6a82d664bd4e84ed026c/cf-units-3.2.0.tar.gz
  sha256: 88a9f140e4157fe4c2d322b5e079046c4c0a7d76cb4950c700a8363bc235074f
requirements:
  host:
    - libudunits2
    - numpy
  run:
    - cftime
    - Jinja2
    - numpy
build:
  script: |
    export UDUNITS2_XML_PATH="/src/packages/.libs/share/udunits/udunits2.xml";
    export CFLAGS="${CFLAGS} -I/src/packages/.libs/include";
    export LDFLAGS="${CFLAGS} -L/src/packages/.libs/lib -lexpat";
about:
  home: https://github.com/SciTools/cf-units
  PyPI: https://pypi.org/project/cf-units
  summary:
    Units of measure as required by the Climate and Forecast (CF) metadata
    conventions
  license: BSD
