package:
  name: charset-normalizer
  version: 3.4.0
  top-level:
    - charset_normalizer
source:
  url: https://files.pythonhosted.org/packages/bf/9b/08c0432272d77b04803958a4598a51e2a4b51c06640af8b8f0f908c18bf2/charset_normalizer-3.4.0-py3-none-any.whl
  sha256: fe9f97feb71aa9896b81973a7bbada8c49501dc73e58a10fcef6663af95e5079
about:
  home: https://github.com/Ousret/charset_normalizer
  PyPI: https://pypi.org/project/charset-normalizer
  summary:
    The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
  license: MIT
