package:
  name: xeofs
  version: 3.0.3
  top-level:
    - xeofs
source:
  url: https://files.pythonhosted.org/packages/15/a8/31652f6a26f7b8e32c9fcf483038f29ae982679de7964cf6f9aac5e568c8/xeofs-3.0.3-py3-none-any.whl
  sha256: ee23faff5ce6cb15e763f16289bd550f6d3695a506b7ee84f1b052b49a4f64b8
requirements:
  run:
    - dask
    - numpy
    - pandas
    - scikit-learn
    - tqdm
    - typing-extensions
    - xarray
    - xarray-datatree
about:
  home: https://github.com/nicrie/xeofs
  PyPI: https://pypi.org/project/xeofs
  summary: Collection of EOF analysis and related techniques for climate science
  license: MIT
