package:
  name: xeofs
  version: 3.0.4
  top-level:
    - xeofs
source:
  url: https://files.pythonhosted.org/packages/00/df/6d625138c0059086cd599de01e28d14a5c0d0963525baf00690ce154fcf9/xeofs-3.0.4-py3-none-any.whl
  sha256: 3343faf9ab01aa092b8642964355165ceb290a9473627f04c75b4a8361cbdcb2
requirements:
  run:
    - dask
    - numpy
    - pandas
    - scikit-learn
    - tqdm
    - typing-extensions
    - xarray
about:
  home: https://github.com/nicrie/xeofs
  PyPI: https://pypi.org/project/xeofs
  summary: Collection of EOF analysis and related techniques for climate science
  license: MIT
