package:
  name: locket
  version: 1.0.0
  top-level:
    - locket
source:
  url: https://files.pythonhosted.org/packages/db/bc/83e112abc66cd466c6b83f99118035867cecd41802f8d044638aa78a106e/locket-1.0.0-py2.py3-none-any.whl
  sha256: b6c819a722f7b6bd955b80781788e4a66a55628b858d347536b7e81325a3a5e3
about:
  home: http://github.com/mwilliamson/locket.py
  PyPI: https://pypi.org/project/locket
  summary: File-based locks for Python on Linux and Windows
  license: BSD-2-Clause
