package:
  name: libaec
  version: 1.1.3

source:
  url: https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.1.3/libaec-v1.1.3.tar.gz
  sha256: 1bafbfaef773bf8f5e5451e6c1f23da36c7199186cc0974fb9874bf723fe4270
  patches:
    - patches/0001-build-only-static-library.patch

build:
  type: static_library
  script: |
    mkdir -p build;

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_INSTALL_INCLUDEDIR=include;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libaec.a ${DISTDIR}
