package:
  name: pint
  version: 0.24.3
  top-level:
    - pint
source:
  url: https://files.pythonhosted.org/packages/3f/2b/abe15c62ef1aece41d0799f31ba97d298aad9c76bc31dd655c387c29f17a/Pint-0.24.3-py3-none-any.whl
  sha256: d98667e46fd03a1b94694fbfa104ec30858684d8ab26952e2a348b48059089bb
requirements:
  run:
    - typing-extensions
about:
  home: https://github.com/hgrecco/pint
  PyPI: https://pypi.org/project/pint
  summary: Physical quantities module
  license: BSD
