package:
  name: pint
  version: 0.24.4
  top-level:
    - pint
source:
  url: https://files.pythonhosted.org/packages/b7/16/bd2f5904557265882108dc2e04f18abc05ab0c2b7082ae9430091daf1d5c/Pint-0.24.4-py3-none-any.whl
  sha256: aa54926c8772159fcf65f82cc0d34de6768c151b32ad1deb0331291c38fe7659
requirements:
  run:
    - flexcache
    - flexparser
    - platformdirs
    - typing-extensions
about:
  home: https://github.com/hgrecco/pint
  PyPI: https://pypi.org/project/pint
  summary: Physical quantities module
  license: BSD
