package:
  name: patsy
  version: 0.5.6
  top-level:
    - patsy
source:
  url: https://files.pythonhosted.org/packages/43/f3/1d311a09c34f14f5973bb0bb0dc3a6e007e1eda90b5492d082689936ca51/patsy-0.5.6-py2.py3-none-any.whl
  sha256: 19056886fd8fa71863fa32f0eb090267f21fb74be00f19f5c70b2e9d76c883c6
requirements:
  run:
    - numpy
    - six
about:
  home: https://github.com/pydata/patsy
  PyPI: https://pypi.org/project/patsy
  summary:
    A Python package for describing statistical models and for building design
    matrices.
  license: 2-clause BSD
