package:
  name: scikit-learn
  version: 1.6.0
  tag:
    - min-scipy-stack
  top-level:
    - sklearn
source:
  url: https://files.pythonhosted.org/packages/fa/19/5aa2002044afc297ecaf1e3517ed07bba4aece3b5613b5160c1212995fc8/scikit_learn-1.6.0.tar.gz
  sha256: 9d58481f9f7499dff4196927aedd4285a0baec8caa3790efbe205f13de37dd6e

build:
  cflags: -Wno-implicit-function-declaration

requirements:
  host:
    - numpy
    - scipy
  run:
    - scipy
    - joblib
    - threadpoolctl

test:
  imports:
    - sklearn
    - sklearn.calibration
    - sklearn.cluster
    - sklearn.compose
    - sklearn.covariance
    - sklearn.cross_decomposition
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.discriminant_analysis
    - sklearn.dummy
    - sklearn.ensemble
    - sklearn.exceptions
    - sklearn.externals
    - sklearn.feature_extraction
    - sklearn.feature_selection
    - sklearn.gaussian_process
    - sklearn.impute
    - sklearn.isotonic
    - sklearn.kernel_approximation
    - sklearn.kernel_ridge
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.mixture
    - sklearn.model_selection
    - sklearn.multiclass
    - sklearn.multioutput
    - sklearn.naive_bayes
    - sklearn.neighbors
    - sklearn.neural_network
    - sklearn.pipeline
    - sklearn.preprocessing
    - sklearn.random_projection
    - sklearn.semi_supervised
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
about:
  home: http://scikit-learn.org
  PyPI: https://pypi.org/project/scikit-learn
  summary: A set of python modules for machine learning and data mining
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - lesteve
