package:
  name: platformdirs
  version: 4.2.0
  top-level:
    - platformdirs
source:
  url: https://files.pythonhosted.org/packages/55/72/4898c44ee9ea6f43396fbc23d9bfaf3d06e01b83698bdf2e4c919deceb7c/platformdirs-4.2.0-py3-none-any.whl
  sha256: 0614df2a2f37e1a662acbd8e2b25b92ccf8632929bc6d43467e17fe89c75e068
about:
  home: https://github.com/platformdirs/platformdirs
  PyPI: https://pypi.org/project/platformdirs
  summary:
    A small Python package for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
  license: MIT
