package:
  name: platformdirs
  version: 4.3.6
  top-level:
    - platformdirs
source:
  url: https://files.pythonhosted.org/packages/3c/a6/bc1012356d8ece4d66dd75c4b9fc6c1f6650ddd5991e421177d9f8f671be/platformdirs-4.3.6-py3-none-any.whl
  sha256: 73e575e1408ab8103900836b97580d5307456908a03e92031bab39e4554cc3fb
about:
  home: https://github.com/platformdirs/platformdirs
  PyPI: https://pypi.org/project/platformdirs
  summary:
    A small Python package for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
  license: MIT
