package:
  name: micropip
  version: 0.7.2
  tag:
    - always
  top-level:
    - micropip

source:
  sha256: d2b63ea316a2a9dcbfeadd4f855d8cec7d54f65b3849e638a7cc627e6d35e4d5
  url: https://files.pythonhosted.org/packages/5a/18/75709500db9e76e1191c410e6b19e04b7ba0fa9c51a188a7625b79f8caf7/micropip-0.7.2-py3-none-any.whl

requirements:
  run:
    - packaging
about:
  home: https://github.com/pyodide/micropip
  PyPI: https://pypi.org/project/micropip
  license: MPL-2.0
