package:
  name: micropip
  # FIXME: JupyterLite pyodide-kernel's piplite's query_package patch needs to
  #        update its signature for v0.7.0
  version: 0.6.1
  tag:
    - always
  top-level:
    - micropip

source:
  sha256: 07df4b2e900385e43f432c5bc791343f9ef34927aa510a9bfce8ee111db4c2b4
  url: https://files.pythonhosted.org/packages/f2/e1/a8a071bc65a3c2a61b5056096086dbe272205279a9bb110567dec242959e/micropip-0.6.1-py3-none-any.whl

requirements:
  run:
    - packaging
about:
  home: https://github.com/pyodide/micropip
  PyPI: https://pypi.org/project/micropip
  license: MPL-2.0
