package:
  name: micropip
  version: 0.9.0
  tag:
    - always
  top-level:
    - micropip

source:
  sha256: d72c3224537a14e5d9d02f29e945bf7cde02404ec744291e8f6a310cedf60b66
  url: https://files.pythonhosted.org/packages/3d/6f/aeef5f7696480704c133206511ff785dd86b76b6eba77391d14de162c1ab/micropip-0.9.0.tar.gz
  patches:
    - patches/0001-relative-index-urls.patch

about:
  home: https://github.com/pyodide/micropip
  PyPI: https://pypi.org/project/micropip
  license: MPL-2.0
