package:
  name: pystac
  version: 1.11.0
  top-level:
    - pystac
source:
  url: https://files.pythonhosted.org/packages/71/5b/60dc94cbf6af2fd3a3d3fae52de7e294819af2dfe7a1bea4d246beb7e0b6/pystac-1.11.0-py3-none-any.whl
  sha256: 10ac7c7b4ea6c5ec8333829a09ec1a33b596f02d1a97ffbbd72cd1b6c10598c1
requirements:
  run:
    - Jinja2
    - jsonschema
    - python-dateutil
    - urllib3
about:
  home: https://github.com/stac-utils/pystac
  PyPI: https://pypi.org/project/pystac
  summary:
    Python library for working with the SpatioTemporal Asset Catalog (STAC)
    specification
  license: Apache-2.0
