package:
  name: antlr4-python3-runtime
  version: 4.13.2
  top-level:
    - antlr4
source:
  url: https://files.pythonhosted.org/packages/33/5f/2cdf6f7aca3b20d3f316e9f505292e1f256a32089bd702034c29ebde6242/antlr4_python3_runtime-4.13.2.tar.gz
  sha256: 909b647e1d2fc2b70180ac586df3933e38919c85f98ccc656a96cd3f25ef3916
about:
  home: https://github.com/parrt/antlr4-python3
  PyPI: https://pypi.org/project/antlr4-python3-runtime
  summary: ANTLR 4.13.2 runtime for Python 3
  license: BSD
