package:
  name: astropy-iers-data
  version: 0.2024.12.9.0.36.21
  top-level:
    - astropy_iers_data
source:
  url: https://files.pythonhosted.org/packages/7a/61/e60f37243022bcad482e0141f7c03ec6f3a69cd6076418aff71e9b32f6d3/astropy_iers_data-0.2024.12.9.0.36.21.tar.gz
  sha256: b8c235b5420702a8e28bb43d94e634aa4bead38d9e72dea03fd0a22b1057817d
about:
  home: https://github.com/astropy/astropy-iers-data
  PyPI: https://pypi.org/project/astropy_iers_data
  summary: IERS Earth Rotation and Leap Second tables for the astropy core package
  license: BSD-3-Clause
