package:
  name: MetPy
  version: 1.6.3
  top-level:
    - metpy
source:
  url: https://files.pythonhosted.org/packages/83/02/289311573657f4dd9832e04df2faa6989d2592036e2fb6990673251778c4/MetPy-1.6.3-py3-none-any.whl
  sha256: 9946436197394d63647aac4310191028707bd644d4a8e41ee310d6d77c0f71f8
requirements:
  run:
    - matplotlib
    - numpy
    - pandas
    - Pint
    - pooch
    - pyproj
    - scipy
    - traitlets
    - xarray
about:
  home: https://github.com/Unidata/MetPy
  PyPI: https://pypi.org/project/MetPy
  summary:
    Collection of tools for reading, visualizing and performing calculations
    with weather data.
  license: BSD-3-Clause
