# Based on https://github.com/petersalomonsen/wasm-git

package:
  name: libgit2
  version: 1.7.1

source:
  url: https://github.com/libgit2/libgit2/archive/refs/tags/v1.7.1.tar.gz
  sha256: 17d2b292f21be3892b704dddff29327b3564f96099a1c53b00edc23160c71327
  patches:
    - patches/0001-emscripten-transport-fs.patch

build:
  type: shared_library
  exports: requested
  script: |
    emcmake cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_FLAGS="-Oz -lz" \
      -DREGEX_BACKEND=regcomp \
      -DSONAME=OFF \
      -DUSE_HTTPS=OFF \
      -DBUILD_SHARED_LIBS=OFF \
      -DTHREADSAFE=OFF \
      -DUSE_SSH=OFF \
      -DBUILD_CLAR=OFF \
      -DBUILD_EXAMPLES=ON \
      .
    emmake make lg2 -j ${PYODIDE_JOBS:-3}

    cp -P examples/liblg2.so ${DISTDIR}/libgit2.so
    cp -P examples/liblg2.so ${WASM_LIBRARY_DIR}/lib/libgit2.so
requirements:
  host:
    - zlib
