package:
  name: shapely
  version: 2.1.0
  top-level:
    - shapely
source:
  url: https://files.pythonhosted.org/packages/source/s/shapely/shapely-2.1.0.tar.gz
  sha256: 2cbe90e86fa8fc3ca8af6ffb00a77b246b918c7cf28677b7c21489b678f6b02e
build:
  vendor-sharedlib: true
  script: |
    export GEOS_CONFIG=${WASM_LIBRARY_DIR}/bin/geos-config
  cxxflags: |
    -fwasm-exceptions
  ldflags: |
    -fwasm-exceptions
requirements:
  run:
    - numpy  # required
  host:
    - geos
    - numpy
test:
  imports:
    - shapely
    - shapely.geos
    - shapely.geometry
    - shapely.ops
    - shapely.prepared
    - shapely.validation
    - shapely.strtree
about:
  home: https://github.com/shapely/shapely
  PyPI: https://pypi.org/project/shapely
  summary: Geometric objects, predicates, and operations
  license: BSD-3-Clause
