package:
  name: Pygments
  version: 2.18.0
  top-level:
    - pygments
source:
  sha256: b8e6aca0523f3ab76fee51799c488e38782ac06eafcf95e7ba832985c8e7b13a
  url: https://files.pythonhosted.org/packages/f7/3f/01c8b82017c199075f8f788d0d906b9ffbbc5a47dc9918a945e13d5a2bda/pygments-2.18.0-py3-none-any.whl
about:
  home: https://pygments.org/
  PyPI: https://pypi.org/project/Pygments
  summary: Pygments is a syntax highlighting package written in Python.
  license: BSD-2-Clause
