package:
  name: click-plugins
  version: 1.1.1
  top-level:
    - click_plugins
source:
  url: https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
  sha256: 5d262006d3222f5057fd81e1623d4443e41dcda5dc815c06b442aa3c02889fc8
requirements:
  run:
    - click
about:
  home: https://github.com/click-contrib/click-plugins
  PyPI: https://pypi.org/project/click-plugins
  summary:
    An extension module for click to enable registering CLI commands via setuptools
    entry-points.
  license: New BSD
