package:
  name: rasterio
  version: 1.4.1
  top-level:
    - rasterio
source:
  url: https://files.pythonhosted.org/packages/5d/e9/92a09209093831ef02a42bb58e3ef73d20e49931ea6043d82c29319780d9/rasterio-1.4.1.tar.gz
  sha256: d750362bb792d2311f94803ff309baec48486ecba75c9b905ea9b1f5eb06ef9f
requirements:
  host:
    - numpy
    - gdal
    - libproj
  run:
    - numpy
    - affine
    - gdal
    - attrs
    - certifi
    - click
    - cligj
    - click-plugins
    - pyparsing
build:
  vendor-sharedlib: true
  script: |
    export PACKAGE_DATA=1
    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG}
    echo ${GDAL_DATA}
    echo ${PROJ_LIB}
about:
  home: https://github.com/rasterio/rasterio
  PyPI: https://pypi.org/project/rasterio
  summary: Fast and direct raster I/O for use with Numpy and SciPy
  license: BSD
