package:
  name: rasterio
  version: 1.4.1
  top-level:
    - rasterio
source:
  url: https://github.com/rasterio/rasterio/archive/1.4.1.tar.gz
  sha256: e91e93179e58f0a9ecd870ba2147c4d8014d98c3f2c34ae1c5510d6cfff92435
requirements:
  host:
    - numpy
    - gdal
    - libproj
  run:
    - numpy
    - affine
    - gdal
    - attrs
    - certifi
    - click
    - cligj
      # - click-plugins # only for rio cli?
build:
  vendor-sharedlib: true
  script: |
    export PACKAGE_DATA=1
    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG}
    echo ${GDAL_DATA}
    echo ${PROJ_LIB}
test:
  imports:
    - rasterio
about:
  home: https://github.com/rasterio/rasterio
  PyPI: https://pypi.org/project/rasterio
  summary: Fast and direct raster I/O for use with Numpy and SciPy
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - kjmalek
