package:
  name: prompt_toolkit
  version: 3.0.48
  top-level:
    - prompt_toolkit
source:
  url: https://files.pythonhosted.org/packages/a9/6a/fd08d94654f7e67c52ca30523a178b3f8ccc4237fce4be90d39c938a831a/prompt_toolkit-3.0.48-py3-none-any.whl
  sha256: f49a827f90062e411f1ce1f854f2aedb3c23353244f8108b89283587397ac10e
requirements:
  run:
    - wcwidth
about:
  home: https://github.com/prompt-toolkit/python-prompt-toolkit
  PyPI: https://pypi.org/project/prompt_toolkit
  summary: Library for building powerful interactive command lines in Python
  license: BSD-3-Clause
