package:
  name: plotly
  version: 5.24.1
  top-level:
    - _plotly_future_
    - _plotly_utils
    - jupyterlab_plotly
    - plotly
source:
  url: https://files.pythonhosted.org/packages/e5/ae/580600f441f6fc05218bd6c9d5794f4aef072a7d9093b291f1c50a9db8bc/plotly-5.24.1-py3-none-any.whl
  sha256: f67073a1e637eb0dc3e46324d9d51e2fe76e9727c892dde64ddf1e1b51f29089
about:
  home: https://plotly.com/python/
  PyPI: https://pypi.org/project/plotly
  summary: An open-source, interactive data visualization library for Python
  license: MIT
