package:
  name: zipp
  version: 3.20.2
  top-level:
    - zipp
source:
  url: https://files.pythonhosted.org/packages/62/8b/5ba542fa83c90e09eac972fc9baca7a88e7e7ca4b221a89251954019308b/zipp-3.20.2-py3-none-any.whl
  sha256: a817ac80d6cf4b23bf7f2828b7cabf326f15a001bea8b1f9b49631780ba28350
about:
  home: https://github.com/jaraco/zipp
  PyPI: https://pypi.org/project/zipp
  summary: Backport of pathlib-compatible object wrapper for zip files
  license: MIT
