package:
  name: zipp
  version: 3.21.0
  top-level:
    - zipp
source:
  url: https://files.pythonhosted.org/packages/b7/1a/7e4798e9339adc931158c9d69ecc34f5e6791489d469f5e50ec15e35f458/zipp-3.21.0-py3-none-any.whl
  sha256: ac1bbe05fd2991f160ebce24ffbac5f6d11d83dc90891255885223d42b3cd931
about:
  home: https://github.com/jaraco/zipp
  PyPI: https://pypi.org/project/zipp
  summary: Backport of pathlib-compatible object wrapper for zip files
  license: MIT
