package:
  name: zipp
  version: 3.17.0
  top-level:
    - zipp
source:
  url: https://files.pythonhosted.org/packages/d9/66/48866fc6b158c81cc2bfecc04c480f105c6040e8b077bc54c634b4a67926/zipp-3.17.0-py3-none-any.whl
  sha256: 0e923e726174922dce09c53c59ad483ff7bbb8e572e00c7f7c46b88556409f31
about:
  home: https://github.com/jaraco/zipp
  PyPI: https://pypi.org/project/zipp
  summary: Backport of pathlib-compatible object wrapper for zip files
  license: "MIT"
