package:
  name: contourpy
  version: 1.3.2
  top-level:
    - contourpy

source:
  url: https://files.pythonhosted.org/packages/source/c/contourpy/contourpy-1.3.2.tar.gz
  sha256: b6945942715a034c671b7fc54f9588126b0b8bf23db2696e3ca8328f3ff0ab54

requirements:
  run:
    - numpy

about:
  home: https://github.org/contourpy/contourpy
  PyPI: https://pypi.org/project/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - ianthomas23
