package:
  name: xarray-datatree
  version: 0.0.15
  top-level:
    - datatree
source:
  url: https://files.pythonhosted.org/packages/cb/e3/6952d37e19b66bd2f18a3de16289ad7da4ef649f6284e07942a5bf5931a8/xarray_datatree-0.0.15-py3-none-any.whl
  sha256: 190d8262061522eeaaa0dc7058b50df7228a615e6d62761150f093518bdad62c
about:
  home: ""
  PyPI: https://pypi.org/project/xarray-datatree
  summary: Hierarchical tree-like data structures for xarray
  license: Apache-2
