package:
  name: numcodecs_wasm
  version: 0.1.6
  tag:
    - rust
  top-level:
    - numcodecs_wasm
source:
  url: https://files.pythonhosted.org/packages/source/n/numcodecs_wasm/numcodecs_wasm-0.1.6.tar.gz
  sha256: f2793787ceae397e8831452dc7067bc3b79a9a271e5fef1c8c95f3f8a7c0195d
about:
  home: https://github.com/juntyr/numcodecs-rs
  PyPI: https://pypi.org/project/numcodecs-wasm
  summary: numcodecs compression for codecs compiled to WebAssembly
  license: MPL-2.0
