package:
  name: numcodecs_wasm
  version: 0.1.5
  tag:
    - rust
  top-level:
    - numcodecs_wasm
source:
  url: https://files.pythonhosted.org/packages/source/n/numcodecs_wasm/numcodecs_wasm-0.1.5.tar.gz
  sha256: 593a6362a37548ab86f2e450a58e010dbd0b2be70f625deadbf155031a4eeeef
about:
  home: https://github.com/juntyr/numcodecs-rs
  PyPI: https://pypi.org/project/numcodecs-wasm
  summary: numcodecs compression for codecs compiled to WebAssembly
  license: MPL-2.0
