package:
  name: numcodecs_wasm
  version: 0.1.4
  tag:
    - rust
  top-level:
    - numcodecs_wasm
source:
  url: https://files.pythonhosted.org/packages/source/n/numcodecs_wasm/numcodecs_wasm-0.1.4.tar.gz
  sha256: ea3245ba0026cdbc22f40709bdda97a39f3988ee18e8f99ee66661f66d2d3a8f
about:
  home: https://github.com/juntyr/numcodecs-rs
  PyPI: https://pypi.org/project/numcodecs-wasm
  summary: numcodecs compression for codecs compiled to WebAssembly
  license: MPL-2.0
