package:
  name: cmcrameri
  version: 1.9
  top-level:
    - cmcrameri
source:
  url: https://files.pythonhosted.org/packages/f9/a2/4c88f17ee50af5093978c4d989936883f959d7d81e1e2fa093863b080c1c/cmcrameri-1.9-py3-none-any.whl
  sha256: daefca10cc405f437ad292bad52f704c2ba8ae692b3e100da8c25f641997e337
about:
  home: https://github.com/callumrollo/cmcrameri
  PyPI: https://pypi.org/project/cmcrameri
  summary: Perceptually uniform colormaps by Fabio Crameri
  license: MIT
