package:
  name: pyfdb
  version: 0.1.1
  top-level:
    - pyfdb
source:
  url: https://files.pythonhosted.org/packages/source/p/pyfdb/pyfdb-0.1.1.tar.gz
  sha256: f27648875074428d26a8ae6c78daf86f6b4fc6333138dd29d582946355a6158e
  patches:
    - patches/0001-findlib.patch
requirements:
  host:
    - libfdb
  run:
    - cffi
    - eccodes
    - packaging
build:
  vendor-sharedlib: true
  post: |
    mkdir -p pyfdb.libs
    cp -P ${WASM_LIBRARY_DIR}/lib/libfdb5.so pyfdb.libs

about:
  home: https://github.com/ecmwf/pyfdb
  PyPI: https://pypi.org/project/pyfdb
  summary: Python interface to FDB
  license: Apache License 2.0
