package:
  name: widgetsnbextension
  version: 4.0.999
  top-level:
    - widgetsnbextension
source:
  url: https://github.com/jupyterlite/pyodide-kernel/archive/refs/tags/v0.4.5.tar.gz
  sha256: d1cd1bebc0796a55b54e30f6c275fa940de0b656afbc5c59cccf41cbcb346e9c
build:
  script: |
    cd ..
    mv widgetsnbextension-4.0.999/packages/pyodide-kernel/py/widgetsnbextension4/widgetsnbextension .
    rm -rf widgetsnbextension-4.0.999
    mv widgetsnbextension widgetsnbextension-4.0.999
about:
  home: http://jupyter.org
  PyPI: https://pypi.org/project/widgetsnbextension
  summary: Jupyter interactive widgets for Jupyter Notebook
  license: BSD 3-Clause License
