package:
  name: widgetsnbextension
  version: 4.0.13
  top-level:
    - widgetsnbextension
source:
  url: https://files.pythonhosted.org/packages/56/fc/238c424fd7f4ebb25f8b1da9a934a3ad7c848286732ae04263661eb0fc03/widgetsnbextension-4.0.13.tar.gz
  sha256: ffcb67bc9febd10234a362795f643927f4e0c05d9342c727b65d2384f8feacb6
build:
  script: |
    cd ..
    mv widgetsnbextension-4.0.13/packages/pyodide-kernel/py/widgetsnbextension4/widgetsnbextension .
    rm -rf widgetsnbextension-4.0.13
    mv widgetsnbextension widgetsnbextension-4.0.13
about:
  home: http://jupyter.org
  PyPI: https://pypi.org/project/widgetsnbextension
  summary: Jupyter interactive widgets for Jupyter Notebook
  license: BSD 3-Clause License
