package:
  name: urllib3
  version: 2.2.1
  top-level:
    - urllib3
source:
  url: https://files.pythonhosted.org/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl
  sha256: 450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d
test:
  imports:
    - urllib3
    - urllib3.contrib.emscripten
about:
  home: ""
  PyPI: https://pypi.org/project/urllib3
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  license: ""
