package:
  name: threadpoolctl
  version: 3.3.0
  top-level:
    - threadpoolctl
source:
  url: https://files.pythonhosted.org/packages/b1/2c/f504e55d98418f2fcf756a56877e6d9a45dd5ed28b3d7c267b300e85ad5b/threadpoolctl-3.3.0-py3-none-any.whl
  sha256: 6155be1f4a39f31a18ea70f94a77e0ccd57dced08122ea61109e7da89883781e
about:
  home: https://github.com/joblib/threadpoolctl
  PyPI: https://pypi.org/project/threadpoolctl
  summary: threadpoolctl
  license: BSD-3-Clause
