package:
  name: executing
  version: 2.1.0
  top-level:
    - executing
source:
  url: https://files.pythonhosted.org/packages/b5/fd/afcd0496feca3276f509df3dbd5dae726fcc756f1a08d9e25abe1733f962/executing-2.1.0-py2.py3-none-any.whl
  sha256: 8d63781349375b5ebccc3142f4b30350c0cd9c79f921cde38be2be4637e98eaf
about:
  home: https://github.com/alexmojaki/executing
  PyPI: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
