package:
  name: cloudpickle
  version: 3.1.0
  top-level:
    - cloudpickle
source:
  sha256: fe11acda67f61aaaec473e3afe030feb131d78a43461b718185363384f1ba12e
  url: https://files.pythonhosted.org/packages/48/41/e1d85ca3cab0b674e277c8c4f678cf66a91cd2cecf93df94353a606fe0db/cloudpickle-3.1.0-py3-none-any.whl
about:
  home: https://github.com/cloudpipe/cloudpickle
  PyPI: https://pypi.org/project/cloudpickle
  summary: Extended pickling support for Python objects
  license: BSD-3-Clause
