package:
  name: docstring_parser
  version: "0.16"
  top-level:
    - docstring_parser
source:
  url: https://files.pythonhosted.org/packages/d5/7c/e9fcff7623954d86bdc17782036cbf715ecab1bec4847c008557affe1ca8/docstring_parser-0.16-py3-none-any.whl
  sha256: bf0a1387354d3691d102edef7ec124f219ef639982d096e26e3b60aeffa90637
about:
  home: https://github.com/rr-/docstring_parser
  PyPI: https://pypi.org/project/docstring_parser
  summary: Parse Python docstrings in reST, Google and Numpydoc format
  license: MIT
