package:
  name: lru-dict
  version: 1.3.0
  top-level:
    - lru
source:
  url: https://files.pythonhosted.org/packages/96/e3/42c87871920602a3c8300915bd0292f76eccc66c38f782397acbf8a62088/lru-dict-1.3.0.tar.gz
  sha256: 54fd1966d6bd1fcde781596cb86068214edeebff1db13a2cea11079e3fd07b6b
about:
  home: https://github.com/amitdev/lru-dict
  PyPI: https://pypi.org/project/lru-dict
  summary: An Dict like LRU container.
  license: MIT
