package:
  name: aiohappyeyeballs
  version: 2.4.4
  top-level:
    - aiohappyeyeballs
source:
  url: https://files.pythonhosted.org/packages/b9/74/fbb6559de3607b3300b9be3cc64e97548d55678e44623db17820dbd20002/aiohappyeyeballs-2.4.4-py3-none-any.whl
  sha256: a980909d50efcd44795c4afeca523296716d50cd756ddca6af8c65b996e27de8
about:
  home: https://github.com/aio-libs/aiohappyeyeballs
  PyPI: https://pypi.org/project/aiohappyeyeballs
  summary: Happy Eyeballs for asyncio
  license: PSF-2.0
