package:
  name: importlib_metadata
  version: 8.5.0
  top-level:
    - importlib_metadata
source:
  url: https://files.pythonhosted.org/packages/a0/d9/a1e041c5e7caa9a05c925f4bdbdfb7f006d1f74996af53467bc394c97be7/importlib_metadata-8.5.0-py3-none-any.whl
  sha256: 45e54197d28b7a7f1559e60b95e7c567032b602131fbd588f1497f47880aa68b
requirements:
  run:
    - zipp
about:
  home: https://github.com/python/importlib_metadata
  PyPI: https://pypi.org/project/importlib_metadata
  summary: Read metadata from Python packages
  license: Apache Software License
