package:
  name: multiurl
  version: 0.3.1
  top-level:
    - multiurl
source:
  url: https://files.pythonhosted.org/packages/cc/12/4e979f71d90ca5625647f93cd484c733a7e8ae4fd9f6d15369613d727301/multiurl-0.3.1.tar.gz
  sha256: c7001437b59d56d4c310d725c3dcfff98c97c4b652893d88989853827465d442
  patches:
    - patches/0001-pyodide-http.patch
requirements:
  run:
    - requests
    - tqdm
    - pytz
    - python-dateutil
    - pyodide-http
about:
  home: https://github.com/ecmwf/multiurl
  PyPI: https://pypi.org/project/multiurl
  summary:
    A package to download several URL as one, as well as supporting multi-part
    URLs
  license: Apache License Version 2.0
