package:
  name: multiurl
  version: 0.3.2
  top-level:
    - multiurl
source:
  url: https://files.pythonhosted.org/packages/b1/ff/f8316584a92cedf69365b0f9a4765dfa6554ccc36cd08e613b827d85b51b/multiurl-0.3.2.tar.gz
  sha256: 8d412bf8efe823916d289523a0891884dabdac3b30d9304f2f915b0fa94ab4e2
requirements:
  run:
    - requests
    - tqdm
    - pytz
    - python-dateutil
about:
  home: https://github.com/ecmwf/multiurl
  PyPI: https://pypi.org/project/multiurl
  summary:
    A package to download several URL as one, as well as supporting multi-part
    URLs
  license: Apache License Version 2.0
