package:
  name: earthkit-plots
  version: 0.2.8
  top-level:
    - earthkit.plots
source:
  url: https://files.pythonhosted.org/packages/da/9c/9c247fc992805204a1aa6128f12f89ba2e4895b2c8e8619406f70ece61c9/earthkit_plots-0.2.8-py3-none-any.whl
  sha256: 16d3e191aae3448b2c6cbdfd0fa2722bb5675bd8cc7913024e2e70812cdb5b76
requirements:
  run:
    - adjustText                     # required, not loaded immediately
    - Cartopy                        # required
    - earthkit-data                  # required
    - earthkit-plots-default-styles  # required
    - earthkit-regrid                # required
    - matplotlib                     # required
    - numpy                          # required
    - pint                           # required
    - plotly                         # required, not loaded immediately
    - pyyaml                         # required
    - scipy                          # required
about:
  home: https://github.com/ecmwf/earthkit-plots
  PyPI: https://pypi.org/project/earthkit-plots
  summary: Interactive meteorological and climate visualisation tools and templates
  license: Apache License 2.0
