package:
  name: earthkit-plots
  version: 0.2.4
  top-level:
    - earthkit.plots
source:
  url: https://files.pythonhosted.org/packages/03/cb/d7b42b9f02d84e6d2473bdae2278af29e4fc87b72a5ac6233695f85e256d/earthkit_plots-0.2.4-py3-none-any.whl
  sha256: 63425126a98e2fb226f65c6fa2ddc4b83cd9da4e8ab408827b85588a667dfce2
requirements:
  run:
    - adjustText
    - Cartopy
    - earthkit-data
    - earthkit-plots-default-styles
    - earthkit-regrid
    - matplotlib
    - numpy
    - pint
    - pyyaml
    - scipy
about:
  home: https://github.com/ecmwf/earthkit-plots
  PyPI: https://pypi.org/project/earthkit-plots
  summary: Interactive meteorological and climate visualisation tools and templates
  license: Apache License 2.0
