package:
  name: earthkit-plots
  version: 0.2.3
  top-level:
    - earthkit.plots
source:
  url: https://files.pythonhosted.org/packages/5b/25/1f03eb77aeff561bd7335b186c67f29644a7675f148aa7480cbe30acd091/earthkit_plots-0.2.3-py3-none-any.whl
  sha256: cd2baf94d5e44343d862aa58b7735d58c503b8bd2df62cfdd94fd01d3767e38b
requirements:
  run:
    - adjustText
    - Cartopy
    - earthkit-data
    - earthkit-plots-default-styles
    - earthkit-regrid
    - matplotlib
    - numpy
    - pint
    - pyyaml
    - scipy
about:
  home: https://github.com/ecmwf/earthkit-plots
  PyPI: https://pypi.org/project/earthkit-plots
  summary: Interactive meteorological and climate visualisation tools and templates
  license: Apache License 2.0
