package:
  name: cfgrib
  version: 0.9.15.0
  top-level:
    - cfgrib
source:
  url: https://files.pythonhosted.org/packages/7d/d7/96b4209c99f1fd6c19f502cebe8c91983c23331c380f3f521250f268ae8c/cfgrib-0.9.15.0-py3-none-any.whl
  sha256: 469cfd25dc173863795e596263b3b6b5ea1402b1715f2b7b1d4b995b40b32c18
requirements:
  run:
    - attrs
    - click
    - eccodes
    - numpy
    - xarray
about:
  home: https://github.com/ecmwf/cfgrib
  PyPI: https://pypi.org/project/cfgrib
  summary:
    Python interface to map GRIB files to the NetCDF Common Data Model following
    the CF Convention using ecCodes.
  license: Apache License Version 2.0
