package:
  name: xhistogram
  version: 0.3.2
  top-level:
    - xhistogram
source:
  url: https://files.pythonhosted.org/packages/18/08/1432dd10193a5d45294bd42042a5631259ee5a12cd2e9075350546d07a03/xhistogram-0.3.2-py3-none-any.whl
  sha256: ad55330d55296d273b3370678223fde0f50085e04cb744c7b3b0bb7702a2c6bf
requirements:
  run:
    - dask
    - numpy
    - xarray
about:
  home: https://github.com/xgcm/xhistogram
  PyPI: https://pypi.org/project/xhistogram
  summary: Fast, flexible, label-aware histograms for numpy and xarray
  license: MIT
