package:
  name: flexcache
  version: "0.3"
  top-level:
    - flexcache
source:
  url: https://files.pythonhosted.org/packages/27/cd/c883e1a7c447479d6e13985565080e3fea88ab5a107c21684c813dba1875/flexcache-0.3-py3-none-any.whl
  sha256: d43c9fea82336af6e0115e308d9d33a185390b8346a017564611f1466dcd2e32
requirements:
  run:
    - typing-extensions
about:
  home: https://github.com/hgrecco/flexcache
  PyPI: https://pypi.org/project/flexcache
  summary: Saves and loads to the cache a transformed versions of a source object.
  license: BSD
