package:
  name: cdsapi
  version: 0.7.4
  top-level:
    - cdsapi
source:
  url: https://files.pythonhosted.org/packages/82/e5/e342d83c7cb3768c4563b02c3af157cf628e8a632fb9ae9605b145feb0ba/cdsapi-0.7.4-py2.py3-none-any.whl
  sha256: 5f70b40e8e777ae956deb6a13d1a3c8d8f099bada91919228adb27c34464144a
requirements:
  run:
    - cads-api-client
    - requests
    - setuptools
    - tqdm
about:
  home: https://github.com/ecmwf/cdsapi
  PyPI: https://pypi.org/project/cdsapi
  summary: Climate Data Store API
  license: Apache 2.0
