package:
  name: pytest
  version: 8.3.4
  tag:
    - core
    - min-scipy-stack
  top-level:
    - _pytest
    - pytest
source:
  url: https://files.pythonhosted.org/packages/11/92/76a1c94d3afee238333bc0a42b82935dd8f9cf8ce9e336ff87ee14d9e1cf/pytest-8.3.4-py3-none-any.whl
  sha256: 50e16d954148559c9a74109af1eaf0c945ba2d8f30f0a3d3335edde19788b6f6
requirements:
  run:
    - iniconfig
    - packaging
    - pluggy
about:
  home: https://docs.pytest.org/en/latest/
  PyPI: https://pypi.org/project/pytest
  summary: "pytest: simple powerful testing with Python"
  license: MIT
