package:
  name: earthkit-geo
  version: 0.3.0
  top-level:
    - earthkit.geo
source:
  url: https://files.pythonhosted.org/packages/78/84/cbe3a0786a4fc102b8a844ebc2f67237c25a568b451b74c1ddcb912983d6/earthkit_geo-0.3.0-py3-none-any.whl
  sha256: 4ea310b66f734a6dea29d8f44031fefc7bfa75de446409e0c7c8ca318c500659
requirements:
  run:
    - Cartopy  # required, not loaded immediately
    - numpy    # required
    - pyproj   # required, not loaded immediately
    - scipy    # required, not loaded immediately
about:
  home: https://github.com/ecmwf/earthkit-geo
  PyPI: https://pypi.org/project/earthkit-geo
  summary: Geospatial computations
  license: Apache License Version 2.0
