package:
  name: referencing
  version: 0.35.1
  top-level:
    - referencing
source:
  url: https://files.pythonhosted.org/packages/b7/59/2056f61236782a2c86b33906c025d4f4a0b17be0161b63b70fd9e8775d36/referencing-0.35.1-py3-none-any.whl
  sha256: eda6d3234d62814d1c64e305c1331c9a3a6132da475ab6382eaa997b21ee75de
requirements:
  run:
    - attrs
    - rpds-py
about:
  home: ""
  PyPI: https://pypi.org/project/referencing
  summary: JSON Referencing + Python
  license: MIT
