package:
  name: ipython
  version: 8.30.0
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/d8/8b/710af065ab8ed05649afa5bd1e07401637c9ec9fb7cfda9eac7e91e9fbd4/ipython-8.30.0.tar.gz
  sha256: cb0a405a306d2995a5cbb9901894d240784a9f341394c6ba3f4fe8c6eb89ff6e
  patches:
    - patches/0001-jupyterlite-preload.patch
requirements:
  run:
    - comm
    - decorator
    - jedi
    - matplotlib-inline
    - prompt_toolkit
    - Pygments
    - stack-data
    - traitlets
    - jupyterlite-preload
about:
  home: https://ipython.org/
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
