package:
  name: ipython
  version: 8.34.0
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/13/18/1a60aa62e9d272fcd7e658a89e1c148da10e1a5d38edcbcd834b52ca7492/ipython-8.34.0.tar.gz
  sha256: c31d658e754673ecc6514583e7dda8069e47136eb62458816b7d1e6625948b5a
  patches:
    - patches/0001-jupyterlite-preload.patch
requirements:
  run:
    - jupyterlite-preload
about:
  home: https://ipython.org/
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
