package:
  name: ipython
  version: 9.0.2
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/source/i/ipython/ipython-9.0.2.tar.gz
  sha256: ec7b479e3e5656bf4f58c652c120494df1820f4f28f522fb7ca09e213c2aab52
  patches:
    - patches/0001-jupyterlite-preload.patch
requirements:
  run:
    - jupyterlite-preload
about:
  home: https://ipython.org/
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
