package:
  name: ipython
  version: 8.29.0
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/85/e0/a3f36dde97e12121106807d80485423ae4c5b27ce60d40d4ab0bab18a9db/ipython-8.29.0.tar.gz
  sha256: 40b60e15b22591450eef73e40a027cf77bd652e757523eebc5bd7c7c498290eb
  patches:
    - patches/0001-jupyterlite-preload.patch
requirements:
  run:
    - comm
    - decorator
    - jedi
    - matplotlib-inline
    - prompt_toolkit
    - pure-eval
    - Pygments
    - stack-data
    - traitlets
    - jupyterlite-preload
about:
  home: https://ipython.org/
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
