package:
  name: ecmwf-opendata
  version: 0.3.14
  top-level:
    - ecmwf.opendata
source:
  url: https://files.pythonhosted.org/packages/a0/61/95554cf79d1d9a64429a9b955d4eaad2ad593333fdefec8d095eaedc07e3/ecmwf-opendata-0.3.14.tar.gz
  sha256: f0704720902103f10d406183a1251754a345c071378681c3171b4c44aad7428a
requirements:
  run:
    - multiurl
about:
  home: https://github.com/ecmwf/ecmwf-opendata
  PyPI: https://pypi.org/project/ecmwf-opendata
  summary: A package to download ECMWF open data
  license: Apache License Version 2.0
