package:
  name: ecmwf-opendata
  version: 0.3.10
  top-level:
    - ecmwf.opendata
source:
  url: https://files.pythonhosted.org/packages/dc/3b/18cdf4a4e1f1511d58aa35124a37d4553645d9c8f59ce766ba87ab2fe9ed/ecmwf-opendata-0.3.10.tar.gz
  sha256: 7bc417f02f4f04b2ab1e4e98508b7c4ce5f5a0ca2bc82317a1a861f20aa54af4
requirements:
  run:
    - multiurl
about:
  home: https://github.com/ecmwf/ecmwf-opendata
  PyPI: https://pypi.org/project/ecmwf-opendata
  summary: A package to download ECMWF open data
  license: Apache License Version 2.0
