package:
  name: field-compression-benchmark
  version: 0.0.13
  top-level:
    - fcbench
source:
  url: https://files.pythonhosted.org/packages/1e/51/54b6c7a6781b1d8d484051f39fe93db4afa2d5981a66ac59247c1aed5d54/field-compression-benchmark-0.0.13.tar.gz
  sha256: a671506ee36c419ae8373388cb89a0414d4deb928fc6a72557bbb94d2a315cc1
  patches:
    - patches/0001-codecs-build.patch
    # we need to build std so that std's libc is compiled to check against the
    #  Pyodide's emscripten version and not the one Rust was built on CI with
    # see https://github.com/rust-lang/rust/issues/131467
    - patches/0002-build-std.patch
build:
  script: |
    # Set up a more modern nightly toolchain with support for emscripten and wasm
    export RUSTUP_TOOLCHAIN="nightly-2024-10-13"  # last 1.83 nightly
    rustup toolchain install ${RUSTUP_TOOLCHAIN}
    rustup target add wasm32-unknown-emscripten --toolchain ${RUSTUP_TOOLCHAIN}
    rustup target add wasm32-unknown-unknown --toolchain ${RUSTUP_TOOLCHAIN}
    rustup component add rust-src --toolchain ${RUSTUP_TOOLCHAIN}

    export RUSTFLAGS="--remap-path-prefix=$(rustc --print=sysroot)/lib/rustlib/src/rust=/rust/1.83"

    # Fetch the pre-built WASM codecs from one of the wheels
    wget https://files.pythonhosted.org/packages/c7/07/97f0eb6f333e89ae983c5e66d06a5e27812cedf531f31ef0afd80fc937bf/field_compression_benchmark-0.0.13-cp312-cp312-manylinux_2_28_x86_64.whl -O fcbench.zip
    unzip -j fcbench.zip fcbench/data/codecs/*.wasm -d data/codecs/
    rm fcbench.zip
requirements:
  executable:
    - rustup
  run:
    - cfgrib  # 0.9.14.1
    - dask  # 2024.12.0
    - matplotlib  # 3.5.2
    - netcdf4  # 1.7.2
    - numcodecs  # 0.13.1
    - numpy  # 1.26.4
    - pint  # 0.24.4
    - xarray  # 2024.11.0
    - xeofs  # 3.0.4
    - xhistogram  # 0.3.2
    - zarr  # 2.18.3
about:
  home: https://github.com/juntyr/field-compression-benchmark
  summary:
    The suite compares the performance of various data compression methods with
    different settings across a variety of variables and their derivatives from
    different GRIB, NetCDF, or Zarr datasets.
  license: MIT OR Apache-2.0
