package:
  name: pytz
  version: "2024.2"
  tag:
    - core
    - min-scipy-stack
  top-level:
    - pytz
source:
  sha256: 31c7c1817eb7fae7ca4b8c7ee50c72f93aa2dd863de768e1ef4245d426aa0725
  url: https://files.pythonhosted.org/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl
about:
  home: http://pythonhosted.org/pytz
  PyPI: https://pypi.org/project/pytz
  summary: World timezone definitions, modern and historical
  license: MIT
