package:
  name: rich-argparse
  version: 1.6.0
  top-level:
    - rich_argparse
source:
  url: https://files.pythonhosted.org/packages/25/45/54b95bb72bb17c27a7252bee5034955020b5869a33918b660ffc29cbf608/rich_argparse-1.6.0-py3-none-any.whl
  sha256: fbe70a1d821b3f2fa8958cddf0cae131870a6e9faa04ab52b409cb1eda809bd7
requirements:
  run:
    - rich
about:
  home: https://github.com/hamdanal/rich-argparse
  PyPI: https://pypi.org/project/rich-argparse
  summary: Rich help formatters for argparse and optparse
  license: MIT License
