package:
  name: pillow
  version: 11.2.1
  top-level:
    - PIL
source:
  sha256: a64dd61998416367b7ef979b73d3a85853ba9bec4c2925f74e588879a58716b6
  url: https://files.pythonhosted.org/packages/source/p/pillow/pillow-11.2.1.tar.gz
  patches:
    - patches/0001-Enable-image-formats.patch
build:
  # RELOCATABLE flag is required because if affects how emscripten build ports.
  cflags: |
    -s RELOCATABLE=1
    -s USE_ZLIB=1
    -s USE_FREETYPE=1
    -s USE_LIBPNG=1
    -s USE_LIBJPEG=1
  ldflags: |
    -ljpeg
  backend-flags: |
    platform-guessing=disable
    zlib=True
    jpeg=True
    freetype=True
    webp=True
    tiff=True
    lcms=False
    xcb=False
    webpmux=False
    jpeg2000=False
    imagequant=False

requirements:
  # Pillow will use `pkg-config` to find and link these libraries.
  host:
    - libwebp
    - libtiff
about:
  home: https://python-pillow.org
  PyPI: https://pypi.org/project/Pillow
  summary: Python Imaging Library (Fork)
  license: HPND
