package:
  name: dask
  version: 2024.10.0
  top-level:
    - dask
source:
  url: https://files.pythonhosted.org/packages/85/ec/0fa1997dd7070a336063663a1305e6967b7c906bd7907f2435c5ad049b0e/dask-2024.10.0-py3-none-any.whl
  sha256: 1ddc27c7967e134b4f8296a488521485a5ac4927cc63e2abfa0b24227b93217f
test:
  imports:
    - dask
requirements:
  run:
    - click
    - cloudpickle
    - importlib_metadata
    - Jinja2
    - packaging
    - partd
    - pyyaml
    - toolz
about:
  home: https://github.com/dask/dask/
  PyPI: https://pypi.org/project/dask
  summary: Parallel PyData with Task Scheduling
  license: BSD
