package:
  name: dask
  version: 2024.12.0
  top-level:
    - dask
source:
  url: https://files.pythonhosted.org/packages/3a/46/9ea782eb1accabad0931d80818fcf8b286bdd1b457ae9c718f039430c489/dask-2024.12.0-py3-none-any.whl
  sha256: e038e87b9f06e7927b81ecde6cf2b49aa699bb902fec11abba5697cb48baeb8d
test:
  imports:
    - dask
requirements:
  run:
    - click
    - cloudpickle
    - fsspec
    - numpy
    - packaging
    - partd
    - pyyaml
    - toolz
about:
  home: https://github.com/dask/dask/
  PyPI: https://pypi.org/project/dask
  summary: Parallel PyData with Task Scheduling
  license: BSD
